### ISSUE TITLE
StrictUndefined fails for tojson filter

### ISSUE THREAD

**Issue by beanaroo** [pallets/jinja#1039]
Using the `tojson` filter on an undefined varaible with `StrictUndefined` raises `TypeError: Object of type StrictUndefined is not JSON serializable` instead of `UndefinedError: 'value' is undefined`.

```python
e = Environment(undefined=StrictUndefined)
t = e.from_string("{{ value|tojson }}")
t.render()
```

```pytb
Traceback (most recent call last):
  File "/opt/pycharm-eap/helpers/pydev/pydevd.py", line 2060, in <module>
    main()
  File "/opt/pycharm-eap/helpers/pydev/pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-eap/helpers/pydev/pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/opt/pycharm-eap/helpers/pydev/pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-eap/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "myscript.py", line 212, in <module>
    main()
  File "myscript.py", line 53, in main
    rendered_plan_path = render_plan(args.latest)
  File "myscript.py", line 91, in render_plan
    plan_renderer.render_recursive()
  File "myscript.py", line 170, in render_recursive
    self.render_file(template)
  File "myscript.py", line 150, in render_file
    rendered_template = self.j2env.get_template(template).render(config)
  File "/usr/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "mytemplate.tf.j2", line 11, in top-level template code
    options = {{ my_missing_dictionary|tojson }}
  File "/usr/lib/python3.7/site-packages/jinja2/filters.py", line 1078, in do_tojson
    return htmlsafe_json_dumps(value, dumper=dumper, **options)
  File "/usr/lib/python3.7/site-packages/jinja2/utils.py", line 565, in htmlsafe_json_dumps
    rv = dumper(obj, **kwargs) \
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type StrictUndefined is not JSON serializable
```

* Python version: 3.7
* Jinja version: 2.10.1

**Comment by davidism** [comment]
I don't understand the issue here. `Undefined` is not JSON. You get an error saying so. What's wrong with that?

**Comment by davidism** [comment]
`json.dumps` doesn't call any special methods, it only does instance checks, so there's nothing to override to make `StrictUndefined` raise an error.

**Comment by davidism** [comment]
Basically, you're asking for an `Undefined` class that raises as soon as it's resolved, which is not possible with the current API. Would using `{{ value|tojson if value is defined }}` instead work for you?

**Comment by davidism** [comment]
Here's a subclass that will raise as soon as it's resolved. Note that it will raise even if whatever is using the value can handle undefined values, such as the `default` filter.

```python
class FailUndefined(Undefined):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._fail_with_undefined_error()
```

**Comment by ztane** [comment]
> json.dumps doesn't call any special methods, it only does instance checks, so there's nothing to override to make StrictUndefined raise an error.

That's not quite true, a default hook could be used

**Comment by beanaroo** [comment]
@davidism Thank you for the clarification.

@ztane I included an example of using an object hook in the original submission (see _edited_ dropdown above). If this is the same as you are suggesting :)
