### ISSUE TITLE
Regression with version 2.10.2

### ISSUE THREAD

**Issue by sbrunner** [pallets/jinja#1069]
I get the following error :-(
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2332, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'jinja2.ext' has no attribute 'bable_extract'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pot-create", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/lingua/extract.py", line 308, in main
    register_babel_plugins()
  File "/usr/local/lib/python3.7/dist-packages/lingua/extractors/babel.py", line 51, in register_babel_plugins
    extractor = entry_point.load(require=True)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2334, in resolve
    raise ImportError(str(exc))
ImportError: module 'jinja2.ext' has no attribute 'bable_extract'
```

**Comment by ThiefMaster** [comment]
It's babel_extract, not bable_extract.

**Comment by ThiefMaster** [comment]
oh, it's a typo in our setup.py ;/

**Comment by davidism** [comment]
oops, hold on

**Comment by ThiefMaster** [comment]
Fixed in 218e77d77da08f045672a2e2abb521ba5c73d2a1, we'll make a new release soon

**Comment by davidism** [comment]
2.10.3 released

**Comment by sbrunner** [comment]
Thanks :-)
