### ISSUE TITLE
Error with template errors with Django and debug

### ISSUE THREAD

**Issue by tomhamiltonstubber** [pallets/jinja#1094]
**Not sure if this should be here or in `django-jinja`, looks like here though.**

This error happens for Authenticated users, where there's an error in rendering the template.

## Expected Behaviour
Error renders properly in browser with stacktrace

## Actual Behaviour
`A server error occurred.  Please contact the administrator.` is shown in the browser, and a long stacktrace in the console.

## Template Code
I created a repo with an easily replicated example:

https://github.com/tomhamiltonstubber/jinja2-error-example

## Full Traceback
```pytb

# The first error I'm deliberately causing

  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tom/repos/jinja-error-replication/JinjaError/main/views.py", line 9, in index
    return render(request, 'index.jinja', {'foo': 'Bar'})
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/django_jinja/backend.py", line 106, in render
    return mark_safe(self.template.render(context))
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "templates/index.jinja", line 1, in top-level template code
    {% extends 'base.jinja' %}
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "templates/index.jinja", line 14, in root
  File "templates/base.jinja", line 11, in root
  File "templates/index.jinja", line 23, in block_content
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/django/views/debug.py", line 94, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/django/views/debug.py", line 333, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/django/views/debug.py", line 264, in get_traceback_data
    frames = self.get_traceback_frames()
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/django/views/debug.py", line 422, in get_traceback_frames
    filename, lineno, 7, loader, module_name,
  File "/home/tom/repos/jinja-error-replication/env/lib/python3.7/site-packages/django/views/debug.py", line 383, in _get_lines_from_file
    context_line = source[lineno]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

And then the same thing * 7.
```

## Your Environment
* Python version: 3.7
* Jinja version: 2.10.2+

**Comment by davidism** [comment]
I can't speak to why Django didn't display a traceback in the browser, you'll need to consult Django about that.

`ValueError: not enough values to unpack (expected 2, got 1)`

`for x, y in foo` where `foo` is a dict is not correct, you'd need to do `in foo.items()`.

**Comment by davidism** [comment]
My guess is that something is getting tripped up in Django due to the way Jinja remaps exceptions from the compiled module back to the source template line numbers.

https://github.com/django/django/blob/ab0fd3f58f751859cc7c5260decf0acca26513bf/django/views/debug.py#L383
