### ISSUE TITLE
Cannot use callables as default arguments for macros

### ISSUE THREAD

**Issue by Naddiseo** [pallets/jinja#110]
Jinja currently does not accept callables for default values of macro arguments

Test case:

```
from jinja2 import Environment, FileSystemLoader
env  = Environment(loader=FileSystemLoader(''))
env.globals.update({'get_int' : lambda: 42})
 t=env.from_string("""
 {% macro test(arg1=get_int()) %}
     {{arg1}}
{% endmacro %}
{{ test(1) }}
""")
print t.render()
```

Throws the following exception:

```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 894, in render
  return self.environment.handle_exception(exc_info, True)
File "<template>", line 3, in top-level template code
NameError: global name 'l_get_int' is not defined
```

**Comment by mitsuhiko** [comment]
This is fixed with #637
