### ISSUE TITLE
Missing markupsafe dependency

### ISSUE THREAD

**Issue by matkoniecz** [pallets/jinja#1103]
## Expected Behavior
Jinja installed as dependency should work.

## Actual Behavior
It is not, crashing on `ModuleNotFoundError: No module named 'markupsafe'` (reported as https://github.com/fsfe/reuse-tool/issues/109 )

Curiously https://github.com/pallets/jinja/blob/master/setup.py#L51 has it as install_requires.

So I would expect that it is installed ( https://packaging.python.org/discussions/install-requires-vs-requirements/ )

Not sure what happens here and how to debug - maybe pip in general or my pip have problems? Or is `install_requires` somehow mangled in this `setup.py`?

## Template Code

I installed and run reuse tool, depending on Jinja 
```jinja
Paste the template code (ideally a minimal example) that causes the issue
(not available for now)
```

## Full Traceback
```pytb
Traceback (most recent call last):
  File "/home/mateusz/.local/bin/reuse", line 6, in <module>
    from reuse._main import main
  File "/home/mateusz/.local/lib/python3.6/site-packages/reuse/_main.py", line 13, in <module>
    from . import (
  File "/home/mateusz/.local/lib/python3.6/site-packages/reuse/header.py", line 18, in <module>
    from jinja2 import Environment, FileSystemLoader, PackageLoader, Template
  File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/usr/lib/python3/dist-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/lib/python3/dist-packages/jinja2/utils.py", line 531, in <module>
    from markupsafe import Markup, escape, soft_unicode
ModuleNotFoundError: No module named 'markupsafe'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/home/mateusz/.local/bin/reuse", line 6, in <module>
    from reuse._main import main
  File "/home/mateusz/.local/lib/python3.6/site-packages/reuse/_main.py", line 13, in <module>
    from . import (
  File "/home/mateusz/.local/lib/python3.6/site-packages/reuse/header.py", line 18, in <module>
    from jinja2 import Environment, FileSystemLoader, PackageLoader, Template
  File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/usr/lib/python3/dist-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/lib/python3/dist-packages/jinja2/utils.py", line 531, in <module>
    from markupsafe import Markup, escape, soft_unicode
ModuleNotFoundError: No module named 'markupsafe'
```

## Your Environment
* Python version: 3.6
* Jinja version: `pip3.6 list | grep -i ji` give me Jinja2 2.8

**Comment by akx** [comment]
How did you install Jinja in the first place? Based on `/usr/lib/python3/dist-packages/`, it was likely installed via something like `apt-get install python-jinja2`, which might give you any random version your distribution felt like packaging.

You can explicitly install a proper version of Jinja2 in your current user environment with

```
pip3 install --user -U jinja2
```
(if that doesn't work, add `--ignore-installed`)

and it should pull in MarkupSafe and friends too.

**Comment by davidism** [comment]
Markupsafe is correctly installed when using pip for me, so there is something else messed up with your installation process.
