### ISSUE TITLE
generate_async() doesn't return an async iterator

### ISSUE THREAD

**Issue by davidbrochart** [pallets/jinja#1150]
## Expected Behavior
`generate_async` should return an async iterator.

## Actual Behavior
It seems to return a generator.

## Template Code
```python
import jinja2
import asyncio

jinja2.Environment(enable_async=True)

async def gen_i():
    for i in range(3):
        yield i
        await asyncio.sleep(0.1)

tpl = jinja2.Template("""\
{% for i in gen_i() %}
{{ i }}
{% endfor %}
""")

async def generate():
    async for m in tpl.generate_async(gen_i=gen_i):
        print(m, end='')

asyncio.run(generate())
```

## Full Traceback
```pytb
Traceback (most recent call last):
  File "async.py", line 22, in <module>
    asyncio.run(generate())
  File "/home/david/miniconda3/envs/jinja/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/david/miniconda3/envs/jinja/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "async.py", line 19, in generate
    async for m in tpl.generate_async(gen_i=gen_i):
  File "/home/david/miniconda3/envs/jinja/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 35, in generate_async
    yield self.environment.handle_exception()
  File "/home/david/miniconda3/envs/jinja/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/david/miniconda3/envs/jinja/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
TypeError: 'async for' requires an object with __aiter__ method, got generator
```

## Your Environment
* Python version: 3.8.1
* Jinja version: 2.11.1

**Comment by mitsuhiko** [comment]
You need to use the instanciated async environment for your template. Use `env = jinja2.Environment(enable_async=True)` and `env.from_string`.

**Comment by davidbrochart** [comment]
Thanks!
