### ISSUE TITLE
Can't handle 'list' and 'dict' typed value in the 'unique' filter

### ISSUE THREAD

**Issue by userlocalhost** [pallets/jinja#1187]
I want to let you know that `TypeError` exception would be happened when `list` and `dict` typed value would be passed to the `unique` filter.

This is a test code that passes variety of typed value to the `unique` filter. When it's run, the last two processes would be fault.
```
import jinja2

expression = """
{%- for val in values|unique -%}
  {{ val }}
{%- endfor %}
"""

env = jinja2.Environment()

env.from_string(expression).render(values=[1,2,3,1])                  # PASS
env.from_string(expression).render(values=['a','b','c','a'])          # PASS
env.from_string(expression).render(values=[(1,), (2,), (3,), (1,)])   # PASS
env.from_string(expression).render(values=[[1], [2], [3], [1]])       # NG
env.from_string(expression).render(values=[{'a':1},{'b':2},{'a':1}])  # NG
```

## Expected Behavior
```
>>> env.from_string(expression).render(values=[[1], [2], [3], [1]])
'[1][2][3]'
```
```
>>> env.from_string(expression).render(values=[{'a':1},{'b':2},{'a':1}])
"{'a': 1}{'b': 2}"
>>> 
```

## Actual Behavior
```
>>> env.from_string(expression).render(values=[[1], [2], [3], [1]])
...
TypeError: unhashable type: 'list'
```
```
>> env.from_string(expression).render(values=[{'a':1},{'b':2},{'a':1}])
...
TypeError: unhashable type: 'dict'
```

## Full Traceback
This is an execution result of above code.
```
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jinja2
>>> 
>>> jinja2.__version__
'3.0.0a1'
>>> 
>>> expression = """
... {%- for val in values|unique -%}
...   {{ val }}
... {%- endfor %}
... """
>>> 
>>> env = jinja2.Environment()
>>> 
>>> env.from_string(expression).render(values=[1,2,3,1])                  # PASS
'123'
>>> env.from_string(expression).render(values=['a','b','c','a'])          # PASS
'abc'
>>> env.from_string(expression).render(values=[(1,), (2,), (3,), (1,)])   # PASS
'(1,)(2,)(3,)'
>>> env.from_string(expression).render(values=[[1], [2], [3], [1]])       # NG
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/dev/jinja/.tox/py36/lib/python3.6/site-packages/jinja2/environment.py", line 1045, in render
    self.environment.handle_exception()
  File "/home/vagrant/dev/jinja/.tox/py36/lib/python3.6/site-packages/jinja2/environment.py", line 787, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 2, in top-level template code
  File "/home/vagrant/dev/jinja/.tox/py36/lib/python3.6/site-packages/jinja2/filters.py", line 367, in do_unique
    if key not in seen:
TypeError: unhashable type: 'list'
>>> env.from_string(expression).render(values=[{'a':1},{'b':2},{'a':1}])  # NG
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/dev/jinja/.tox/py36/lib/python3.6/site-packages/jinja2/environment.py", line 1045, in render
    self.environment.handle_exception()
  File "/home/vagrant/dev/jinja/.tox/py36/lib/python3.6/site-packages/jinja2/environment.py", line 787, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 2, in top-level template code
  File "/home/vagrant/dev/jinja/.tox/py36/lib/python3.6/site-packages/jinja2/filters.py", line 367, in do_unique
    if key not in seen:
TypeError: unhashable type: 'dict'
>>> 
```

## Your Environment
Python version: 3.6
Jinja version: 3.0.0a1

**Comment by davidism** [comment]
This isn't a bug, it's a standard behavior of Python. If your project needs a unique filter that handles these types, you can add a custom filter, or process the data before rendering it.
