### ISSUE TITLE
No module named 'pkg_resources'

### ISSUE THREAD

**Issue by toddmowen** [pallets/jinja#1192]
I suspect that #1169 might not have been reverted cleanly in #1182, since some behaviour has changed for me between 2.11.1 and 2.11.2. No doubt this bites me early and hard because I'm using [pex](https://github.com/pantsbuild/pex) to package my application. But if the issue is similar to pantsbuild/pex#631, then it would be caused by Jinja2 not explicitly declaring the dependency on `setuptools`.

Anyway, concrete details as per template...

## Expected Behavior

My application was running without exceptions with 2.11.1.

## Actual Behavior

Built with 2.11.2, when the application is run I encounter:

```
ModuleNotFoundError: No module named 'pkg_resources'
```

## Template Code

N/A

## Full Traceback

```
[18:13:41][Step 1/1] Traceback (most recent call last):
[18:13:41][Step 1/1]   File "/mnt/app/work/71de4152dc3eb41f/myservice2prod-cp37-cp37m-linux_x86_64.pex/.bootstrap/pex/pex.py", line 396, in execute
[18:13:41][Step 1/1]   File "/mnt/app/work/71de4152dc3eb41f/myservice2prod-cp37-cp37m-linux_x86_64.pex/.bootstrap/pex/pex.py", line 328, in _wrap_coverage
[18:13:41][Step 1/1]   File "/mnt/app/work/71de4152dc3eb41f/myservice2prod-cp37-cp37m-linux_x86_64.pex/.bootstrap/pex/pex.py", line 359, in _wrap_profiling
[18:13:41][Step 1/1]   File "/mnt/app/work/71de4152dc3eb41f/myservice2prod-cp37-cp37m-linux_x86_64.pex/.bootstrap/pex/pex.py", line 447, in _execute
[18:13:41][Step 1/1]   File "/mnt/app/work/71de4152dc3eb41f/myservice2prod-cp37-cp37m-linux_x86_64.pex/.bootstrap/pex/pex.py", line 544, in execute_entry
[18:13:41][Step 1/1]   File "/mnt/app/work/71de4152dc3eb41f/myservice2prod-cp37-cp37m-linux_x86_64.pex/.bootstrap/pex/pex.py", line 551, in execute_module
[18:13:41][Step 1/1]   File "/usr/local/lib/python3.7/runpy.py", line 208, in run_module
[18:13:41][Step 1/1]     return _run_code(code, {}, init_globals, run_name, mod_spec)
[18:13:41][Step 1/1]   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
[18:13:41][Step 1/1]     exec(code, run_globals)
[18:13:41][Step 1/1]   File "/mnt/app/work/71de4152dc3eb41f/myservice2prod-cp37-cp37m-linux_x86_64.pex/myservice2prod.py", line 11, in <module>
[18:13:41][Step 1/1]   File "/mnt/app/work/71de4152dc3eb41f/myservice2prod-cp37-cp37m-linux_x86_64.pex/lib/main.py", line 16, in main
[18:13:41][Step 1/1]   File "/mnt/app/work/71de4152dc3eb41f/myservice2prod-cp37-cp37m-linux_x86_64.pex/lib/main.py", line 34, in readiness_report
[18:13:41][Step 1/1]   File "/mnt/app/work/71de4152dc3eb41f/myservice2prod-cp37-cp37m-linux_x86_64.pex/lib/main.py", line 52, in create_report
[18:13:41][Step 1/1]   File "/mnt/app/work/71de4152dc3eb41f/myservice2prod-cp37-cp37m-linux_x86_64.pex/lib/readiness.py", line 27, in format_readiness_report
[18:13:41][Step 1/1]   File "/mnt/app/work/71de4152dc3eb41f/myservice2prod-cp37-cp37m-linux_x86_64.pex/lib/readiness.py", line 15, in format_report
[18:13:41][Step 1/1]   File "/root/.pex/installed_wheels/d2252becc26cb1cd2188f5504f8ba31b5d69b513/Jinja2-2.11.2-py2.py3-none-any.whl/jinja2/loaders.py", line 233, in __init__
[18:13:41][Step 1/1]     from pkg_resources import DefaultProvider
[18:13:41][Step 1/1] ModuleNotFoundError: No module named 'pkg_resources'
```

## Your Environment
* Python version: 3.7.2
* Jinja version: 2.11.2

**Comment by davidism** [comment]
The revert was clean. pkg_resources is provided by setuptools. Jinja, and pretty much every library until very very recently, assumed the presence of setuptools because it was installed by default. If pex is not supplying setuptools, and you're using `PackageLoader`, you'll want to specify setuptools as a requirement in your project.

The most I would change in a new release is to issue a clearer message at runtime, like "setuptools is required to use PackageLoader." Jinja wouldn't add it as a required dependency.
