### ISSUE TITLE
FileExistsError with FileSystemBytecodeCache

### ISSUE THREAD

**Issue by fili** [pallets/jinja#1205]
Trying to utilize [jinja2.FileSystemBytecodeCache](https://jinja.palletsprojects.com/en/2.11.x/api/#jinja2.FileSystemBytecodeCache) in Flask

## Expected Behavior
I expected it to work without throwing exceptions. 

Caches should assist the user in getting the content faster, not prevent the user from getting the content in the first place. I had this error now several times in the last few weeks across several different GAE instances on python 3.8 and users are given a 500 error. 

## Actual Behavior
It throws a FileExistsError, which ironically is what a cache is all about ;) Still, I would expect maybe an except situation in the codebase here to avoid a 500 error to the end user. 

## Flask Code
```
app.jinja_env.bytecode_cache = FileSystemBytecodeCache('/tmp', '__jinja2_%s.cache')
```

## Full Traceback
```
  File "/layers/google.python.pip/pip/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/layers/google.python.pip/pip/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/layers/google.python.pip/pip/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/layers/google.python.pip/pip/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/layers/google.python.pip/pip/jinja2/loaders.py", line 134, in load
    bcc.set_bucket(bucket)
  File "/layers/google.python.pip/pip/jinja2/bccache.py", line 169, in set_bucket
    self.dump_bytecode(bucket)
  File "/layers/google.python.pip/pip/jinja2/bccache.py", line 255, in dump_bytecode
    f = open(self._get_cache_filename(bucket), "wb")
FileExistsError: [Errno 17] File exists: '/tmp/__jinja2_25b991d3c43c9d1d74bf5439fde5a14250a2b526.cache'
```

## Your Environment
* Python version: 3.8 on GAE Standard
* Jinja version: 2.11

**Comment by fili** [comment]
Testing this code snippet to get around the error (still pops up frequently).

```
try: 
        app.jinja_env.bytecode_cache = FileSystemBytecodeCache('/tmp', '__jinja2_%s.cache')
except FileExistsError:
        FileSystemBytecodeCache().clear()  # clearing bytecodecache to avoid another error
```

**Comment by amy-lei** [comment]
Hi! I was wondering if it'd be possible to share more code snippets (such as the template codes or more of the Flask app). I'm trying to reproduce the error, although it's been with simple routes and templates so far

**Comment by fili** [comment]
@amy-lei love to but the code is under NDA. That having said, the snippet above seems to have reduced the errors significantly. Occasionally it still pops up but from like daily error messages it now has gone to once per week or so.

**Comment by davidism** [comment]
Closing as unable to provide a minimal reproducible example.

**Comment by fili** [comment]
Maybe this more complete trace from today will help, as it includes examples of template imports and blocks without the actual code.

```
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/layers/google.python.pip/pip/flask_caching/__init__.py", line 436, in decorated_function
    rv = f(*args, **kwargs)
  File "/srv/main.py", line 91, in home
    render_template(template_name, **context)
  File "/layers/google.python.pip/pip/flask/templating.py", line 137, in render_template
    return _render(
  File "/layers/google.python.pip/pip/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/layers/google.python.pip/pip/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/layers/google.python.pip/pip/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/layers/google.python.pip/pip/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/srv/templates/home.html", line 2, in top-level template code
    {% import "macros.html" as macros %}
  File "/srv/templates/base.html", line 35, in top-level template code
    {% block body %}{% endblock %}
  File "/srv/templates/home.html", line 343, in block "body"
    {% include 'footer.html' %}
  File "/layers/google.python.pip/pip/jinja2/bccache.py", line 169, in set_bucket
    self.dump_bytecode(bucket)
  File "/layers/google.python.pip/pip/jinja2/bccache.py", line 255, in dump_bytecode
    f = open(self._get_cache_filename(bucket), "wb")
FileExistsError: [Errno 17] File exists: '/tmp/__jinja2_623f0deeb7d19c7a28b4e71e87c35fd8b4548dcc.cache'
```

As can be seen here about home.html
- extends on base.html
- imports macros.html (on top of the file, after extending base.html)
- includes footer.html inside the block "body" (which is extended from base.html)

base.html
- includes an empty block "body"

footer.html
- just some repetitive HTML, no special jinja2 tags

macros.html
- includes form macros, similar to https://jinja.palletsprojects.com/en/2.11.x/templates/#macros

Keep in mind that the majority (>99%) of requests does not raise this error. This error is raised only once in a while so this might also be a race condition issue on GAE.

**Comment by davidism** [comment]
I'm sorry, we can't help without an example to reproduce it reliably. It appears to be an issue with GAE, please report it to them.
