### ISSUE TITLE
docs: unclear what is the recommended way to load templates?

### ISSUE THREAD

**Issue by mhansen** [pallets/jinja#1211]
Hi there! This is an experience report of a first-time integrator with jinja2, I'm not sure what the solution should be, but I'll share a confusing bit - trying to get hello world of templates working.

A bunch of this is perhaps silly mistakes but I'm imagining if I'm having trouble with this probably others might be too?

I came to https://jinja.palletsprojects.com/en/2.11.x/api/ and - yay! There's an example at the top:

```
from jinja2 import Environment, PackageLoader, select_autoescape
env = Environment(
    loader=PackageLoader('yourapplication', 'templates'),
    autoescape=select_autoescape(['html', 'xml'])
)
```

So I pasted this into my file `infosrc/make_output.py`:
```
#!/usr/bin/env python3
import jinja2
env = jinja2.Environment(
    loader=jinja2.PackageLoader('yourapplication', 'templates'),
    autoescape=jinja2.select_autoescape(['html.j2']),
)
template = env.get_template('output.html.j2')
print(template.render(formats={}, descriptions={}))
```

And I ran it with `./make_output.py`, but got this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 360, in get_provider
    module = sys.modules[moduleOrReq]
KeyError: 'yourapplication'
```

I don't really have an application name - it's just this python script.

I did a search, found a [StackOverflow where someone else is confused by this](https://stackoverflow.com/questions/14276829/html-templating-using-jinja2-lost), and the accepted answer is to use the folder name.

So I set it to the directory name `infosrc`:

```
    loader=jinja2.PackageLoader('infosrc', 'templates'),
```

I get the same error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 360, in get_provider
    module = sys.modules[moduleOrReq]
KeyError: 'infosrc'
```

I thought, maybe I need a `__init__.py` file in the directory? So I added one, and reran again, getting the same error.

I looked again at the docs:

> This will create a template environment with the default settings and a loader that looks up the templates in the templates folder inside the yourapplication python package. Different loaders are available and you can also write your own if you want to load templates from a database or other resources.

I'm still pretty confused - I don't have any python packages, I only have a one-file script.

I tried using the filename of the script directly - `make_output` - and then my template was output twice! I wondered, maybe `template.render` defaults to printing to stdout, and then I'm printing it again? Docs say no. This honestly had me doubting my sanity - later I figured out that it was because the `PackageLoader` was re-importing and thus re-running the script.

So I thought I'd try the other loaders. The second stackoverflow (non-accepted) actually has more upvotes: to just use `FileSystemLoader` instead. So I did - I got `FileSystemLoader` working because it didn't require me to specify a package. Fantastic! But it was a bit of a bumpy start for hello world :-)

And I got a bit confused at which Loader to use:

* `PackageLoader` [is advertised as](https://jinja.palletsprojects.com/en/2.11.x/api/#basics) "The simplest way to configure Jinja to load templates for your application", but `FileSystemLoader` has fewer params you need to get right, so `FileSystemLoader` seems simpler to me? I'm not clear on what benefits `PackageLoader` has over `FileSystemLoader`. Maybe it doesn't depend on current working directory?

* `FileSystemLoader`'s docs say "This loader can find templates in folders on the file system and is the preferred way to load them." -- does that mean `FileSystemLoader` is preferred over `PackageLoader` for loading from a 'templates' directory? It seems not, because the recommendation at the [top of the page](https://jinja.palletsprojects.com/en/2.11.x/api/#basics) is to use `PackageLoader`.

I think there's some opportunities to make hello world easier here. Here's some ideas:

* Perhaps in the first example note that the file is `yourapplication.py`?
* Perhaps use `FilesystemLoader` as the simplest example, or remove the "The simplest way" text?
* Maybe add some discussion about when to use `FileSystemLoader` vs `PackageLoader` - what are the benefits of loading from packages vs filesystem? CWD-independence maybe?

**Comment by mhansen** [comment]
Thanks - looks like this removes the 'preferred way to load them' language from FileSystemLoader, and explanations are given for why PackageLoader is better (resolving the absolute path). This is a big improvement, thank you!

I think one issue is left outstanding: I think the first example on the page, if copy/pasted, will result in this:

```
from jinja2 import Environment, PackageLoader, select_autoescape
env = Environment(
    loader=PackageLoader("yourapp"),
    autoescape=select_autoescape()
)
template = env.get_template("mytemplate.html")
print(template.render(the="variables", go="here"))
```

Which will reimport yourapp.py, printing out the template twice.

I know you mention "This loader only requires that yourapp is importable" but when the code examples given aren't re-importable I expect many people will still fall into this trap (I certainly would).

**Comment by mhansen** [comment]
Forked off #1239 for the followup issue described above.
