### ISSUE TITLE
Custom Loader based on BaseLoader code comments seems not to work

### ISSUE THREAD

**Issue by tenuki** [pallets/jinja#1256]
## Expected Behavior
I could write a simple Loader with a fixed template subclassing BaseLoader.

I was using this with no problems:
```python
def render_template(file_name, **context):
    return jinja2.Environment(
        loader=jinja2.FileSystemLoader('templates/')
    ).get_template(file_name).render(context)
```

But I wanted to embed my templates with my source-code, so I changed took one basic base template with no dependencies and put it in code and try to use this loader:

```python
class MyLoader(BaseLoader):
    def get_source(self, environment, template):
        fname = "template.html"
        if template!=fname:
            print("looknig for: ", template)
            raise TemplateNotFound(template)
        return Template(TEMPLATE_DATA), fname, False
        # return TEMPLATE, fname, False

def render_template(file_name, **context):
    env = jinja2.Environment(loader=MyLoader)
    tempalte = env.get_template(file_name)
    return tempalte.render(context)
```
and it failed with the exception below.

When I checked BaseLoader code it shows this code, I assumed it would work, and I adapted to my case: 

```python
class MyLoader(BaseLoader):
    def __init__(self, path):
        self.path = path

    def get_source(self, environment, template):
        fname = "template.html"
        if template!=fname:
            print("looknig for: ", template)
            raise TemplateNotFound(template)
        path = '/home/aweil/xxtest/templates/template.html'
        mtime = getmtime(path)
        with file(path) as f:
            source = f.read().decode('utf-8')
        return source, path, lambda: mtime == getmtime(path)
```

But it returns the same error.  What would be a minimal Loader and which would be the proper way to use it "outside" flask?
thanks

## Actual Behavior
When I try to use that, following given code, I get: 
AttributeError: 'Environment' object has no attribute 'get_source'

## Template Code
In this case template doesn't matter.. 
```jinja
TEMPLATE_DATA = """<!DOCTYPE html><html>
<head>
<title>{{title}}</title>
</head>
</html>
"""
```

## Full Traceback
```pytb
Paste the full traceback in case there is an exception
Traceback (most recent call last):
  File "wrap.py", line 96, in <module>
    print(render_template('template.html', **data))
  File "wrap.py", line 67, in render_template
    tempalte = env.get_template(file_name)
  File "/home/aweil/xxtest/venv/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/aweil/xxtest/venv/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/aweil/xxtest/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
AttributeError: 'Environment' object has no attribute 'get_source'
```

## Your Environment
* Python version:
Python 3.7.2

* Jinja version:
Jinja2==2.11.2

**Comment by tenuki** [comment]
My problem was I were not passing a MyLoader instance..

```diff
def render_template(file_name, **context):
    return jinja2.Environment(
-        loader=jinja2.MyLoader
+        loader=jinja2.MyLoader()
    ).get_template(file_name).render(context)
```
