### ISSUE TITLE
Debugging in PyCharm when a "namespace" is in use throws exceptions

### ISSUE THREAD

**Issue by ShaheedHaque** [pallets/jinja#1302]
PyCharm allows breakpoints to be set in Jinja templates. I'm using this with Django under PyCharm, and normally this works fine. However, when a "namespace" is used, the any attempt to set a breakpoint ends up throwing an exception like this:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/Jinja2-3.0.0a1-py3.8.egg/jinja2/utils.py", line 648, in __getattribute__
    return self.__attrs[name]

During handling of the above exception ('__class__'), another exception occurred:
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.8/dist-packages/django_jinja-2.6.0-py3.8.egg/django_jinja/backend.py", line 63, in render
    return mark_safe(self._process_template(self.template.render, context, request))
  File "/usr/local/lib/python3.8/dist-packages/django_jinja-2.6.0-py3.8.egg/django_jinja/backend.py", line 109, in _process_template
    return handler(context)
  File "/usr/local/lib/python3.8/dist-packages/Jinja2-3.0.0a1-py3.8.egg/jinja2/environment.py", line 1045, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/dist-packages/Jinja2-3.0.0a1-py3.8.egg/jinja2/environment.py", line 787, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/main/srhaque/Innovatieltd/source/templates/generic_confirm_delete.html.jinja", line 3, in top-level template code
    {% import 'generic_macros.html.jinja' as macros %}
  File "/main/srhaque/Innovatieltd/source/templates/base_site.html.jinja", line 1, in top-level template code
    {% extends "base.html.jinja" %}
  File "/main/srhaque/Innovatieltd/source/templates/base.html.jinja", line 100, in top-level template code
    {% block content %}
  File "/main/srhaque/Innovatieltd/source/templates/generic_confirm_delete.html.jinja", line 21, in block 'content'
    {% set ns = namespace(count=0) %}
  File "/main/srhaque/Innovatieltd/source/templates/generic_confirm_delete.html.jinja", line 21, in block 'content'
    {% set ns = namespace(count=0) %}
  File "_pydevd_bundle/pydevd_cython.pyx", line 1179, in _pydevd_bundle.pydevd_cython.SafeCallWrapper.__call__
    <source code not available>
  File "_pydevd_bundle/pydevd_cython.pyx", line 620, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
    <source code not available>
  File "_pydevd_bundle/pydevd_cython.pyx", line 932, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
    <source code not available>
  File "_pydevd_bundle/pydevd_cython.pyx", line 855, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
    <source code not available>
  File "/main/srhaque/pycharm-2020.1/plugins/python/helpers/pydev/pydevd_plugins/jinja2_debug.py", line 340, in get_breakpoint
    new_frame = Jinja2TemplateFrame(frame)
  File "/main/srhaque/pycharm-2020.1/plugins/python/helpers/pydev/pydevd_plugins/jinja2_debug.py", line 124, in __init__
    self.f_locals = self.collect_context(frame)
  File "/main/srhaque/pycharm-2020.1/plugins/python/helpers/pydev/pydevd_plugins/jinja2_debug.py", line 139, in collect_context
    elif v and not _is_missing(v):
  File "/main/srhaque/pycharm-2020.1/plugins/python/helpers/pydev/pydevd_plugins/jinja2_debug.py", line 173, in _is_missing
    if item.__class__.__name__ == 'MissingType':
  File "/usr/local/lib/python3.8/dist-packages/Jinja2-3.0.0a1-py3.8.egg/jinja2/utils.py", line 650, in __getattribute__
    raise AttributeError(name)

Exception Type: AttributeError at /paiyroll/paydefinition/13899/delete/
Exception Value: __class__
```
The variables (as displayed by Django) at this point look like this:
![image](https://user-images.githubusercontent.com/4881193/96053746-06ed2000-0e78-11eb-998a-bf0d30e086e3.png)

Repro
=====
To replicate:

1. create a template like this, and view it in PyCharm:
   ```
   hi
    {% set ns = namespace(count=0) %}
   ```
1. Observe that the template emits "hi".
1. Set a breakpoint on the "namespace" line.
1. The template hangs, emitting the exception shown

Environment:

- Python version: 3.8 with Django and PyCharm
- Jinja version: Jinja2-3.0.0a1-py3.8.egg

**Comment by ThiefMaster** [comment]
Creating a namespace is not really special. It's really just a set statement calling a function.

Does it happen for other `set` statements as well? In any case it sounds more like a bug in their debugger...

**Comment by ShaheedHaque** [comment]
Other "set"s work just fine, but I take your point about it likely being their debugger.

And indeed it seems this is tracked here: https://youtrack.jetbrains.com/issue/PY-34796
