### ISSUE TITLE
Illegal chars in tracebacks of pre-compiled templates

### ISSUE THREAD

**Issue by wkornewald** [pallets/jinja#135]
We use `template_environment.compile_templates(path, zip=None, ignore_errors=False)` to precompile our templates. Then, we use `Environment(loader=ModuleLoader(path), auto_reload=False, cache_size=100, extensions=[...], autoescape=True)`. When an exception appears in our precompiled templates we get tracebacks that contain raw snippets from (binary) .pyc files (which break the logger on App Engine due to illegal characters, so no traceback is shown at all):

```
Traceback (most recent call last):
  ...
  File "...\jinja2\environment.py", line 896, in render
    return self.environment.handle_exception(exc_info, True)
  File "...\_generated_templates\tmpl_3ab23a37ff2f5d3f0397c032c9981f48158748e3.pyc", line 1, in top-level template code
    ♥ó
  File "...\_generated_templates\tmpl_fddd151b6369c0b932932650cbe0dbf7f0a62ce8.pyc", line 27, in top-level template code
    <div id="content" style="width: 100%; height: 100%; margin: 0; padding: 0;">
  File "...\_generated_templates\tmpl_3ab23a37ff2f5d3f0397c032c9981f48158748e3.pyc", line 6, in block "js"
     Z
   ...
```

**Comment by davidism** [comment]
The issue is that `debug.fake_exc_info` generates a traceback using the name of the template. Python itself is what's pulling a line out of that file to show, and it doesn't care what the contents of the file is.

When using `ModuleLoader`, the template's filename is the name of the imported file, rather than the name of the source template (which isn't available). On Python 2, pyc files can be loaded directly, in which case Python will try to read binary data as text for the traceback. This doesn't appear to happen on Python 3 (Jinja won't generate pyc files, and the ones Python generates don't seem to affect it).

This isn't visible in your example, but another issue is revealed when not loading pyc files. Since the template file isn't loaded, Jinja shouldn't be remapping the line numbers, it should be showing the line in the compiled file that failed. For example, a template that just has one line actually raises an error on line 13 of the compiled file. If the remapping is applied, the traceback shows the irrelevant first line of the compiled code.

Jinja should be checking whether the source is actually available before applying line remapping. I'm not sure how to solve the binary traceback on Python 2, Jinja might have to open the template and check if it has the pyc magic bytes.
