### ISSUE TITLE
TypeError: unhashable type: 'Config' (regression)

### ISSUE THREAD

**Issue by The-Compiler** [pallets/jinja#1376]
When installing the current git master of jinja, with a trivial Flask application:

```python
import flask

app = flask.Flask(__name__)

@app.route('/')
def test():
    return flask.render_template('test.html')
```

and then:

- Creating an empty `template/test.html`
- Running `FLASK_APP=test flask run`
- Loading the page and reloading it in the browser

This happens:

```pytb
Traceback (most recent call last):
  File ".../site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File ".../site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File ".../site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File ".../site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File ".../site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File ".../site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File ".../test.py", line 7, in test
    return flask.render_template('test.html')
  File ".../site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File ".../site-packages/jinja2/environment.py", line 898, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File ".../site-packages/jinja2/environment.py", line 851, in get_template
    return self._load_template(name, self.make_globals(globals))
  File ".../site-packages/jinja2/environment.py", line 815, in _load_template
    new_globals = globals.items() - template.globals.items()
TypeError: unhashable type: 'Config'
```

This is caused by #1244 / 40a312e80f4f1b25f201293c3f1a840a1b88191d - the commit before that (f71f5ebab2e76c5ee6f5f705a2703f3891e762bc) works fine. Reproducible with Python 3.6.13, 3.7.10, 3.8.8 and 3.9.2.

**Comment by The-Compiler** [comment]
Thanks for the quick fix - I can confirm things are working fine again! :+1:
