### ISSUE TITLE
Add typing_extensions to requirements/typing.in

### ISSUE THREAD

**Issue by DrewDevereux** [pallets/jinja#1424]
jinja imports ``typing_extensions``, but doesn't list it as a requirement, forcing downstream packages to explicitly add it to their own requirements.

**Comment by davidism** [comment]
This is a dependency of mypy. That said, it's not a runtime dependency, so we won't add it to `install_requires`.

**Comment by DrewDevereux** [comment]
Yes, I see. Very strange that, even wth jinja2 installed, sphinx will
```
Traceback (most recent call last):
  File "/home/docs/my_env/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/my_env/lib/python3.8/site-packages/sphinx/application.py", line 277, in __init__
    self._init_builder()
  File "/home/docs/my_env/lib/python3.8/site-packages/sphinx/application.py", line 332, in _init_builder
    self.builder.init()
  File "/home/docs/my_env/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 219, in init
    self.init_templates()
  File "/home/docs/my_env/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 262, in init_templates
    self.templates.init(self, self.theme)
  File "/home/docs/my_env/lib/python3.8/site-packages/sphinx/jinja2glue.py", line 178, in init
    self.environment = SandboxedEnvironment(loader=self,
  File "/home/docs/my_env/lib/python3.8/site-packages/jinja2/sandbox.py", line 253, in __init__
    super().__init__(*args, **kwargs)
  File "/home/docs/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 361, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/home/docs/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/home/docs/my_env/lib/python3.8/site-packages/jinja2/utils.py", line 212, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
  File "/home/docs/my_env/lib/python3.8/site-packages/jinja2/ext.py", line 21, in <module>
    import typing_extensions as te
ModuleNotFoundError: No module named 'typing_extensions'

Exception occurred:
  File "/home/docs/my_env/lib/python3.8/site-packages/jinja2/ext.py", line 21, in <module>
    import typing_extensions as te
ModuleNotFoundError: No module named 'typing_extensions'
```
