### ISSUE TITLE
'Token' object has no attribute 'test' error during template parsing on Python 3.6

### ISSUE THREAD

**Issue by danmaftei** [pallets/jinja#1459]
Following the Flask tutorial. I got to the templates part (https://flask.palletsprojects.com/en/2.0.x/tutorial/templates/) but accessing the registration page results in a 500 server error, apparently due to Jinja failing to parse the template.

I replaced the template with something trivial (`<div>hello</div>`) and it worked fine. When I replaced it with `<div>{{foo}}</div>` or `<div>{% block foo %}{% endblock %}</div>` I got the same error.

Stack trace:

```
127.0.0.1 - - [02/Jun/2021 22:47:49] "GET /auth/register HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dm/Documents/cs/bookclub/book_club/auth.py", line 78, in login
    return render_template('auth/login.html')
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/jinja2/environment.py", line 749, in compile
    source = self._parse(source, name, filename)
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/jinja2/environment.py", line 606, in _parse
    return Parser(self, source, name, filename).parse()
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/jinja2/parser.py", line 1038, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/jinja2/parser.py", line 1021, in subparse
    rv = self.parse_statement()
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/jinja2/parser.py", line 175, in parse_statement
    return f()  # type: ignore
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/jinja2/parser.py", line 326, in parse_extends
    node.template = self.parse_expression()
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/jinja2/parser.py", line 523, in parse_expression
    return self.parse_condexpr()
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/jinja2/parser.py", line 528, in parse_condexpr
    expr1 = self.parse_or()
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/jinja2/parser.py", line 543, in parse_or
    left = self.parse_and()
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/jinja2/parser.py", line 552, in parse_and
    left = self.parse_not()
  File "/Users/dm/Documents/cs/bookclub/bk-env/lib/python3.6/site-packages/jinja2/parser.py", line 560, in parse_not
    if self.stream.current.test("name:not"):
AttributeError: 'Token' object has no attribute 'test'
```

Environment:

- Python version: 3.6
- Jinja version: 3.0.1

On Python 3.8 this works fine.

**Comment by sunnypranay** [comment]
In my case, I had to downgrade the Jinja version.

**Comment by davidism** [comment]
I can't reproduce this issue. I created a virtualenv for Python 3.6, installed the tutorial project, and went to the `login` page shown in your traceback. The login page, and all other pages, rendered successfully.

I also did `from jinja2.lexer import Token` and confirmed that it does have a `test()` method.

**Comment by sunnypranay** [comment]
The problem specifically arises when we use template inheritance.

**Comment by davidism** [comment]
The tutorial does use template inheritance. When reporting an issue, please include a minimal reproducible example.

**Comment by sunnypranay** [comment]
Hi, their @davidism I can understand. could check for the below example.

application.py

```
from flask import Flask, render_template, request

app = Flask(__name__)


@app.route('/', methods=["GET", "POST"])
def home():
    return render_template("index.html")


if __name__ == '__main__':
    app.run()

```
index.html

```
{% extends "layout.html" %}

{% block body %}
<p>Testing template inheritance</p>
{% endblock %}
```

layout.html

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

```
This is  my pip freeze output

```
click==8.0.1
colorama==0.4.4
dataclasses==0.8
Flask==2.0.1
importlib-metadata==4.5.0
itsdangerous==2.0.1
Jinja2==3.0.1
MarkupSafe==2.0.1
typing-extensions==3.10.0.0
Werkzeug==2.0.1
zipp==3.4.1

```

Python version I am using

```
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
```

The error message I got 

```
 * Serving Flask app 'application' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2021-06-07 19:47:17,124] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "D:\Projects\template inheritance\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Projects\template inheritance\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Projects\template inheritance\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Projects\template inheritance\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:/Projects/template inheritance/application.py", line 8, in home
    return render_template("index.html")
  File "D:\Projects\template inheritance\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "D:\Projects\template inheritance\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\Projects\template inheritance\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "D:\Projects\template inheritance\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "D:\Projects\template inheritance\venv\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "D:\Projects\template inheritance\venv\lib\site-packages\jinja2\environment.py", line 749, in compile
    source = self._parse(source, name, filename)
  File "D:\Projects\template inheritance\venv\lib\site-packages\jinja2\environment.py", line 606, in _parse
    return Parser(self, source, name, filename).parse()
  File "D:\Projects\template inheritance\venv\lib\site-packages\jinja2\parser.py", line 1038, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "D:\Projects\template inheritance\venv\lib\site-packages\jinja2\parser.py", line 1021, in subparse
    rv = self.parse_statement()
  File "D:\Projects\template inheritance\venv\lib\site-packages\jinja2\parser.py", line 175, in parse_statement
    return f()  # type: ignore
  File "D:\Projects\template inheritance\venv\lib\site-packages\jinja2\parser.py", line 326, in parse_extends
    node.template = self.parse_expression()
  File "D:\Projects\template inheritance\venv\lib\site-packages\jinja2\parser.py", line 523, in parse_expression
    return self.parse_condexpr()
  File "D:\Projects\template inheritance\venv\lib\site-packages\jinja2\parser.py", line 528, in parse_condexpr
    expr1 = self.parse_or()
  File "D:\Projects\template inheritance\venv\lib\site-packages\jinja2\parser.py", line 543, in parse_or
    left = self.parse_and()
  File "D:\Projects\template inheritance\venv\lib\site-packages\jinja2\parser.py", line 552, in parse_and
    left = self.parse_not()
  File "D:\Projects\template inheritance\venv\lib\site-packages\jinja2\parser.py", line 560, in parse_not
    if self.stream.current.test("name:not"):
AttributeError: 'Token' object has no attribute 'test'
127.0.0.1 - - [07/Jun/2021 19:47:17] "GET / HTTP/1.1" 500 -
```

Thanks in advance.

**Comment by davidism** [comment]
The relevant issue appears to be that Python 3.6.0's `typing.Namedtuple` doesn't support methods:

> Changed in version 3.6.1: Added support for default values, methods, and docstrings.

I'd strongly advise upgrading your Python version, either to the latest 3.6.x or to at least 3.7. Python 3.6 goes end of life December 2021, which means it will no longer be supported by cpython or us.

**Comment by ThiefMaster** [comment]
also, 3.6.0 is almost 5 years old. using 3.6.x is ok if there's a strong reason for it, but using 3.6.0 isn't. (also from a security point of view)

**Comment by davidism** [comment]
I couldn't build 3.6.0 locally and still get pip to work (I have a feeling it was an issue with outdated openssl settings). I had to do `docker pull python:3.6.0`, which isn't even listed on the hub page as existing.

**Comment by sunnypranay** [comment]
Thanks @davidism for the update. I will consider updating my python to the latest 3.6.x or 3.7 version.
