### ISSUE TITLE
Filters that return a generator object have reduced useability or fail

### ISSUE THREAD

**Issue by andy-maier** [pallets/jinja#1471]
I describe this problem for the `select` filter, which returns a generator object. Several other filters also return generator objects, for example `selectattr`, or `map` (the list is probably incomplete).

That causes errors and unexpected behavior when using the result in subsequent filters.

Consider the following standalone test code:
```
import jinja2

template = "{{ ['a', 'b', 'c'] | select('equalto', 'b') }}"

env = jinja2.Environment()
tpl = env.from_string(template)
print(tpl.render())
```

As written, this prints:
```
<generator object select_or_reject at 0x10b1fec10>
```
which not very user friendly and requires subsequent filters just to have a digestible result.

For example, with `template = "{{ ['a', 'b', 'c'] | select('equalto', 'b') }} | list"`, it materializes the generator into a list and prints:
```
['b']
```

However, if the input object for the select filter is a dict, there is no subsequent filter that simply resolves the result into dict.

With `template = "{{ ['a', 'b', 'c'] | select('equalto', 'b') }} | tojson"` it fails because JSON serialization does not work with a generator:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/maiera/virtualenvs/vpc38/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/maiera/virtualenvs/vpc38/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/maiera/virtualenvs/vpc38/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/Users/maiera/virtualenvs/vpc38/lib/python3.8/site-packages/jinja2/filters.py", line 1260, in do_tojson
    return htmlsafe_json_dumps(value, dumper=dumper, **options)
  File "/Users/maiera/virtualenvs/vpc38/lib/python3.8/site-packages/jinja2/utils.py", line 619, in htmlsafe_json_dumps
    dumper(obj, **kwargs)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type generator is not JSON serializable
```

Even the `pprint` filter which is described as printing the object for debugging, prints just the repr() of the generator object:
```
template = "{{ ['a', 'b', 'c'] | select('equalto', 'b') }} | pprint"
...
<generator object select_or_reject at 0x106c71c10>
```

It seems to me that returning generator objects from filters is simply not a good idea. In the best case, it requires users to apply additional filters just to see a result. In the worst case, filters one would expect to work, raise an exception.

**Comment by davidism** [comment]
I don't plan to change this. Returning generators is essential to operate on very large / infinite data sets. This is how Python works as well. For example, `json.dumps(map(int, values))` would raise the same type of error in Python.
