### ISSUE TITLE
Range within a jinja template raises UndefinedError

### ISSUE THREAD

**Issue by chayim** [pallets/jinja#1507]
Although there are [examples](https://jinja.palletsprojects.com/en/2.10.x/templates/) of using range in a template, the following does not work:

### jinja
```
import jinja2
tl = jinja2.FileSystemLoader(h)
env = jinja2.Environment(loader=tl)
tmpl = tl.load(name='myfile.tmpl', environment=env)
```

### template examples
```
{% for i in range(5) %}
{% endfor %}

{% for i in range(0, 5) %}
{% endfor %}

{% set foo = 15
{% for i in range(0, foo) %}
{% endfor %}
```

## Exception

Note, it's documented in all jinja versions listed below. The following is raised:

```
Traceback (most recent call last):
  File "/data/repos/redis/redis-composer/runner.py", line 110, in <module>
    generate(conf, opts.DESTDIR, opts.ENV, ports)
  File "/data/repos/redis/redis-composer/runner.py", line 49, in generate
    generated = tmpl.render(context)
  File "/data/repos/redis/redis-composer/venv39/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/data/repos/redis/redis-composer/venv39/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/data/repos/redis/redis-composer/composer.tmpl", line 9, in top-level template code
    {% for r in range(0, v|int) %}
  File "/data/repos/redis/redis-composer/venv39/lib/python3.9/site-packages/jinja2/utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'range' is undefined
```

Environment:

- Python version: 3.8.3, 3.9.7, 3.10.0
- Jinja version: 2.10.0, 2.11.3, 3.0.2

**Comment by mkrizek** [comment]
This appears to be expected as you have not provided the `globals` parameter to the `load` method, see https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.BaseLoader.load.

I am not sure what you are trying to achieve but perhaps following https://jinja.palletsprojects.com/en/3.0.x/api/#basics would result in the output you would expect?

**Comment by davidism** [comment]
You're doing things backwards. You should be passing the loader to `Environment` and calling `env.get_template`, not pass the environment to `loader.load`. The environment manages the globals.
