### ISSUE TITLE
Python 3.11 traceback format changed, tests fail

### ISSUE THREAD

**Issue by hroncok** [pallets/jinja#1526]
When running jinja's tests with Python 3.11.0a1, two tests fail because the exception format has changed.

To reproduce, run tox:

```
$ tox -e py311
```
Alternativelly, you can limit the number of tests:

```
$ tox -e py311 -- tests/test_debug.py
```

Expected behavior: tests pass.

Actual behavior:

```
GLOB sdist-make: .../jinja/setup.py
py311 inst-nodeps: .../jinja/.tox/.tmp/package/1/Jinja2-3.1.0.dev0.zip
py311 installed: attrs==21.2.0,iniconfig==1.1.1,Jinja2 @ file://.../jinja/.tox/.tmp/package/1/Jinja2-3.1.0.dev0.zip,MarkupSafe==2.0.1,packaging==21.2,pluggy==1.0.0,py @ https://github.com/pytest-dev/py/archive/refs/heads/master.zip,pyparsing==2.4.7,pytest==6.2.5,toml==0.10.2
py311 run-test-pre: PYTHONHASHSEED='705390215'
py311 run-test: commands[0] | pytest -v --tb=short --basetemp=.../jinja/.tox/py311/tmp tests/test_debug.py
============================= test session starts ==============================
platform linux -- Python 3.11.0a1, pytest-6.2.5, py-1.10.1, pluggy-1.0.0 -- .../jinja/.tox/py311/bin/python
cachedir: .tox/py311/.pytest_cache
rootdir: .../jinja, configfile: setup.cfg
collecting ... collected 7 items

tests/test_debug.py::TestDebug::test_runtime_error FAILED                [ 14%]
tests/test_debug.py::TestDebug::test_syntax_error PASSED                 [ 28%]
tests/test_debug.py::TestDebug::test_regular_syntax_error FAILED         [ 42%]
tests/test_debug.py::TestDebug::test_pickleable_syntax_error PASSED      [ 57%]
tests/test_debug.py::TestDebug::test_include_syntax_error_source PASSED  [ 71%]
tests/test_debug.py::TestDebug::test_local_extraction PASSED             [ 85%]
tests/test_debug.py::TestDebug::test_get_corresponding_lineno_traceback PASSED [100%]

=================================== FAILURES ===================================
_________________________ TestDebug.test_runtime_error _________________________
tests/test_debug.py:35: in test_runtime_error
    self.assert_traceback_matches(
tests/test_debug.py:26: in assert_traceback_matches
    assert (
E   AssertionError: Traceback did not match:
E     
E     Traceback (most recent call last):
E       File ".../jinja/tests/test_debug.py", line 22, in assert_traceback_matches
E         callback()
E         ^^^^^^^^^^
E       File ".../jinja/tests/test_debug.py", line 32, in test
E         tmpl.render(fail=lambda: 1 / 0)
E         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E       File ".../jinja/.tox/py311/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
E         self.environment.handle_exception()
E         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E       File ".../jinja/.tox/py311/lib/python3.11/site-packages/jinja2/environment.py", line 925, in handle_exception
E         raise rewrite_traceback_stack(source=source)
E         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E       File ".../jinja/tests/res/templates/broken.html", line 2, in <module>
E         {{ fail() }}
E         ^^^^^^^^^^^^
E       File ".../jinja/tests/test_debug.py", line 32, in <lambda>
E         tmpl.render(fail=lambda: 1 / 0)
E                                  ~~^~~
E     ZeroDivisionError: division by zero
E     
E     expected:
E     
E       File ".*?broken.html", line 2, in (top-level template code|<module>)
E         \{\{ fail\(\) \}\}
E       File ".*debug?.pyc?", line \d+, in <lambda>
E         tmpl\.render\(fail=lambda: 1 / 0\)
E     ZeroDivisionError: (int(eger)? )?division (or modulo )?by zero
E     
E   assert None is not None
_____________________ TestDebug.test_regular_syntax_error ______________________
tests/test_debug.py:65: in test_regular_syntax_error
    self.assert_traceback_matches(
tests/test_debug.py:26: in assert_traceback_matches
    assert (
E   AssertionError: Traceback did not match:
E     
E     Traceback (most recent call last):
E       File ".../jinja/tests/test_debug.py", line 22, in assert_traceback_matches
E         callback()
E         ^^^^^^^^^^
E       File ".../jinja/tests/test_debug.py", line 63, in test
E         raise TemplateSyntaxError("wtf", 42)
E         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E     jinja2.exceptions.TemplateSyntaxError: wtf
E       line 42
E     
E     expected:
E     
E       File ".*debug.pyc?", line \d+, in test
E         raise TemplateSyntaxError\("wtf", 42\)
E     (jinja2\.exceptions\.)?TemplateSyntaxError: wtf
E       line 42
E   assert None is not None
=========================== short test summary info ============================
FAILED tests/test_debug.py::TestDebug::test_runtime_error - AssertionError: T...
FAILED tests/test_debug.py::TestDebug::test_regular_syntax_error - AssertionE...
========================= 2 failed, 5 passed in 0.03s ==========================
ERROR: InvocationError for command .../jinja/.tox/py311/bin/pytest -v --tb=short --basetemp=.../jinja/.tox/py311/tmp tests/test_debug.py (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py311: commands failed
```

Environment:

- Python version: 3.11.0a1
- Jinja version: main branch @ f72597b8ccce73f963eafec2cdcd5a51b4b3e2ad as well as 3.0.1 or 3.0.2 version with https://github.com/pallets/jinja/pull/1525 applied to see the actual difference in the traebacks

I will look at a possible fixer.

**Comment by hroncok** [comment]
Fix ready in https://github.com/pallets/jinja/pull/1527
