### ISSUE TITLE
MarkupSafe on 2.1.0 breaks Jinja

### ISSUE THREAD

**Issue by MichaelVoelkel** [pallets/jinja#1590]
The dependency of MarkupSafe just says >=2 but this breaks with the recent update to Jinja.

```
Traceback (most recent call last):
[23](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:23)
  File "/usr/local/bin/lintly", line 8, in <module>
[24](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:24)
    sys.exit(main())
[25](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:25)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
[26](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:26)
    return self.main(*args, **kwargs)
[27](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:27)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
[28](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:28)
    rv = self.invoke(ctx)
[29](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:29)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
[30](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:30)
    return ctx.invoke(self.callback, **ctx.params)
[31](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:31)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
[32](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:32)
    return callback(*args, **kwargs)
[33](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:33)
  File "/usr/local/lib/python3.9/site-packages/lintly/cli.py", line 74, in main
[34](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:34)
    build.execute()
[35](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:35)
  File "/usr/local/lib/python3.9/site-packages/lintly/builds.py", line 76, in execute
[36](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:36)
    diff = self.get_pr_diff()
[37](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:37)
  File "/usr/local/lib/python3.9/site-packages/lintly/builds.py", line 86, in get_pr_diff
[38](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:38)
    return self.git_client.get_pr_diff(self.config.pr)
[39](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:39)
  File "/usr/local/lib/python3.9/site-packages/lintly/backends/github.py", line 171, in get_pr_diff
[40](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:40)
    diff = client.get(diff_url, headers={'Accept': GITHUB_DIFF_HEADER})
[41](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:41)
  File "/usr/local/lib/python3.9/site-packages/lintly/backends/github.py", line 85, in get
[42](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:42)
    return self._do_request('get', url, data, headers)
[43](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:43)
  File "/usr/local/lib/python3.9/site-packages/lintly/backends/github.py", line 112, in _do_request
[44](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:44)
    raise NotFoundError(response.content, status_code=response.status_code)
[45](https://github.com/MichaelVoelkel/lintly-flake8-github-action/runs/5247805255?check_suite_focus=true#step:4:45)
lintly.backends.errors.NotFoundError: b'{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/pulls#get-a-pull-request"}'
```

I stumbled upon it by using Lintly that depends on Jinja2.

**Comment by MichaelVoelkel** [comment]
Erm, your source depends on `>=2.0`, this is a dependency of Jinja and it breaks Jinja's code, how is this something I should do when using Jinja?
