### ISSUE TITLE
Breaking change in 3.1.0 (upgrading from 3.0.3) 

### ISSUE THREAD

**Issue by shyam-habarakada** [pallets/jinja#1627]
I just noticed that our jinja2 scripts started to fail with the upgrade to 3.1.0

```
[INFO] Running: jinja2 --format=yaml --strict template.yaml variables.yaml > output.yaml
[153](https://git.lab.smartsheet.com/team-halo/edge-proxy-config/-/jobs/3785256#L153)Traceback (most recent call last):
[154](https://git.lab.smartsheet.com/team-halo/edge-proxy-config/-/jobs/3785256#L154)  File "/usr/bin/jinja2", line 8, in <module>
[155](https://git.lab.smartsheet.com/team-halo/edge-proxy-config/-/jobs/3785256#L155)    sys.exit(main())
[156](https://git.lab.smartsheet.com/team-halo/edge-proxy-config/-/jobs/3785256#L156)  File "/usr/lib/python3.7/site-packages/jinja2cli/cli.py", line 424, in main
[157](https://git.lab.smartsheet.com/team-halo/edge-proxy-config/-/jobs/3785256#L157)    sys.exit(cli(opts, args))
[158](https://git.lab.smartsheet.com/team-halo/edge-proxy-config/-/jobs/3785256#L158)  File "/usr/lib/python3.7/site-packages/jinja2cli/cli.py", line 314, in cli
[159](https://git.lab.smartsheet.com/team-halo/edge-proxy-config/-/jobs/3785256#L159)    out.write(render(template_path, data, extensions, opts.strict))
[160](https://git.lab.smartsheet.com/team-halo/edge-proxy-config/-/jobs/3785256#L160)  File "/usr/lib/python3.7/site-packages/jinja2cli/cli.py", line 221, in render
[161](https://git.lab.smartsheet.com/team-halo/edge-proxy-config/-/jobs/3785256#L161)    keep_trailing_newline=True,
[162](https://git.lab.smartsheet.com/team-halo/edge-proxy-config/-/jobs/3785256#L162)  File "/usr/lib/python3.7/site-packages/jinja2/environment.py", line 363, in __init__
[163](https://git.lab.smartsheet.com/team-halo/edge-proxy-config/-/jobs/3785256#L163)    self.extensions = load_extensions(self, extensions)
[164](https://git.lab.smartsheet.com/team-halo/edge-proxy-config/-/jobs/3785256#L164)  File "/usr/lib/python3.7/site-packages/jinja2/environment.py", line 117, in load_extensions
[165](https://git.lab.smartsheet.com/team-halo/edge-proxy-config/-/jobs/3785256#L165)    extension = t.cast(t.Type["Extension"], import_string(extension))
[166](https://git.lab.smartsheet.com/team-halo/edge-proxy-config/-/jobs/3785256#L166)  File "/usr/lib/python3.7/site-packages/jinja2/utils.py", line 149, in import_string
[167](https://git.lab.smartsheet.com/team-halo/edge-proxy-config/-/jobs/3785256#L167)    return getattr(__import__(module, None, None, [obj]), obj)
[168](https://git.lab.smartsheet.com/team-halo/edge-proxy-config/-/jobs/3785256#L168)AttributeError: module 'jinja2.ext' has no attribute 'autoescape'
```

**Comment by davidism** [comment]
That's correct, the changelog calls this out, and its use was previously issuing a `DeprecationWarning`. You'll need to remove the `autoescape` extension, it has been built-in to Jinja for some time now.

**Comment by shyam-habarakada** [comment]
@davidism I'm not directly specifying `autoescape` but am using `jinja2-cli`, and I looked at the code and they appear to indeed use autoesape. Opened an issue here https://github.com/mattrobenolt/jinja2-cli/issues/101
