### ISSUE TITLE
`random` filter no longer accepts `seed` keyword argument

### ISSUE THREAD

**Issue by bobf** [pallets/jinja#1635]
The `random` filter seems to no longer accept a `seed` keyword argument.

This has broken some Ansible builds. The same builds were working on 2022/03/23 (one day before release of `3.1.0`). What confuses me is that downgrading to `3.0.3` does not appear to fix the problem. I will continue to investigate this and update the ticket if I get any more information (perhaps another dependency is responsible here ?).

```python
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jinja2
>>> jinja2.__version__
'3.1.0'
>>> jinja2.Template("{{ [1, 2, 3] | random(seed='example') }}").render()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
TypeError: do_random() got an unexpected keyword argument 'seed'
```

- Python version: `3.8.10`
- Jinja version: `3.1.0`

**Comment by bobf** [comment]
@davidism You are indeed correct. Thanks for the info and sorry for not being more thorough.

However, I can confirm that downgrading Jinja2 to `3.0.3` does fix the Ansible builds, so the `3.1.0` release does result in some breakage. I'll create a bug report in Ansible but wanted to give you a heads up in case this ends up coming back to you (via Ansible devs).

Thanks again for the help - at least our builds are running now. :+1:
