### ISSUE TITLE
Undefined error when compiling expressions with different operators

### ISSUE THREAD

**Issue by odino** [pallets/jinja#1683]
Looks like the behavior of undefined variables changes as we use different operators? I assume it's because we don't really know whether the variable can be used in the expression eg. None > 1 would throw an error in python. 

```
>>> import jinja2
>>> from jinja2 import Environment

>>> Environment().compile_expression("foo == 1")()
False

>>> Environment().compile_expression("foo > 1")()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1567, in __call__
    consume(self._template.root_render_func(context))  # type: ignore
  File "/home/alex/.local/lib/python3.8/site-packages/jinja2/utils.py", line 114, in consume
    for _ in iterable:
  File "<template>", line 13, in root
  File "/home/alex/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'foo' is undefined

>>> Environment(undefined=jinja2.ChainableUndefined).compile_expression("foo > 1")()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1567, in __call__
    consume(self._template.root_render_func(context))  # type: ignore
  File "/home/alex/.local/lib/python3.8/site-packages/jinja2/utils.py", line 114, in consume
    for _ in iterable:
  File "<template>", line 13, in root
  File "/home/alex/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'foo' is undefined
```

Is there some sort of a fix where we could override this behavior? eg. when a variable, part of an expression, is not defined, the expression evaluates to `False`?

eg. `foo > 5 or 123` could return `123`

Environment:

- Python version:3.8.10
- Jinja version: 3.2.1

**Comment by davidism** [comment]
Use the `is undefined` test.

**Comment by odino** [comment]
@davidism what do you mean by that?

I can do

```
var and var > 5
```

though I'd just like to:

```
var > 5
```

and have that evaluate to false.
