### ISSUE TITLE
AttributeError: module 'posixpath' has no attribute 'sep'

### ISSUE THREAD

**Issue by tilman19** [pallets/jinja#1697]
On one of my systems the loader command fails with "AttributeError: module 'posixpath' has no attribute 'sep'. 
It can actually run the code but not use the debugger within PyCharm 2022.1.3. This will trigger the exception.

The full stack trace looks like the following:

```
Traceback (most recent call last):
  File "/mycode/venv/lib/python3.10/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/mycode/venv/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/mycode/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/mycode/venv/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/mycode/venv/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/mycode/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mycode/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mycode/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/mycode/venv/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/mycode/src/myproject/cli/commands/build.py", line 106, in build
    _create_all_docker_files(project_config, build_mode=mode, services=services)
  File "/mycode/src/myproject/cli/commands/build.py", line 118, in _create_all_docker_files
    _create_docker_file(service, project_config, build_mode)
  File "/mycode/src/myproject/cli/commands/build.py", line 135, in _create_docker_file
    dockerfile_template = get_jinja_env().get_template('Dockerfile.jinja')
  File "/mycode/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/mycode/venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/mycode/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/mycode/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 195, in get_source
    pieces = split_template_path(template)
  File "/mycode/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 32, in split_template_path
    os.path.sep in piece
AttributeError: module 'posixpath' has no attribute 'sep'
```

**Expected result:** No error when running the code in the debugger just as when running without debugger.

It seems `os.path.sep` is the problem  here. According to the official Python documentation `os.sep` is the primary source (https://docs.python.org/3/library/os.html#os.sep). Chaning from `os.path.sep` to `os.sep` fixes this issue.

Environment used:
* Python 3.10.5
* Jinja2 3.1.2
* PyCharm 2022.1 on Arch Linux

**Comment by davidism** [comment]
I can't reproduce this issue with the information provided. Be sure to provide a minimal reproducible example when reporting an issue.

```
$ python3.10 --version
3.10.5
$ python
>>> import os.path
os.path.sep
```

I also ran the following in a simple script with the PyCharm 2022.1.3 debugger on Linux and did not get the reported error.

```python
from jinja2.loaders import FileSystemLoader
loader = FileSystemLoader(".")
print(loader.list_templates())
```

**Comment by kevin-brown** [comment]
Highly suspect this ticket is related. It suggests this is system-specific and likely tied to newer Python versions.

https://github.com/stub42/pytz/issues/72

I saw the related PR which supposedly fixes the issue.

**Comment by tilman19** [comment]
Reproducing this bug is indeed tricky. It occurs on one system and not on another very similar system. But it also seems this does not only happen here with jinja, as @kevin-brown mentioned. 
PyTest has had the same bug as well: https://github.com/pytest-dev/pytest/issues/9791 

Using `os.sep` instead of `os.path.sep` is closer to the Python documentation as well, so I don’t see a showstopper here. But it’s also not upon me to decide if the merge request is fine.
