### ISSUE TITLE
jinja does not install correctly

### ISSUE THREAD

**Issue by Irtiza90** [pallets/jinja#1724]
just created a new virtual enviornment and tried to install jinja, and it didn't work
```bash
&> py -m venv "./venv"
&> venv/Scripts/activate.ps1
(venv)
&> pip install -U jinja
Collecting jinja
  Using cached Jinja-1.2.tar.gz (252 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\NLN\AppData\Local\Temp\pip-install-b9dd8u9s\jinja_4d60d28c738145038ba2a0959fc89831\setup.py", line 28
          except DistutilsError, e:
                 ^^^^^^^^^^^^^^^^^
      SyntaxError: multiple exception types must be parenthesized
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

Environment:

- Os: Windows 10
- Python version: 3.10.7
- Jinja version: 1.2

**Comment by Irtiza90** [comment]
My bad i had to write `pip install jinja2`
