### ISSUE TITLE
`SyntaxError: multiple exception types must be parenthesized` at installation

### ISSUE THREAD

**Issue by victorpaleologue** [pallets/jinja#1821]
On Mac OS 13.2.1, Apple silicon, using `pip` in a fresh `pipenv` (via `pipenv shell`):
```
$ pip3 install jinja
Collecting jinja
  Using cached Jinja-1.2.tar.gz (252 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/bm/80tk36qx7n39khrmvplw_lf00000gn/T/pip-install-vqqfaq40/jinja_f2db7fe72f424717ba603b1d64781aea/setup.py", line 28
          except DistutilsError, e:
                 ^^^^^^^^^^^^^^^^^
      SyntaxError: multiple exception types must be parenthesized
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
A workaround would be appreciated in the meantime.

**Comment by victorpaleologue** [comment]
I've just noticed that: https://github.com/pallets/jinja/issues/1724.
My bad.
