### ISSUE TITLE
Exception Handling when using jinja2.DictLoader

### ISSUE THREAD

**Issue by cmason3** [pallets/jinja#2065]
If I use the `jinja2.FileSystemLoader` and there is an error within my Jinja2 template then the Exception is raised and it reports the file that caused the issue, e.g:

```
  File "test.j2", line 1, in template
    Test {% x
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'x'.
```

However, if I use `jinja2.DictLoader` then when it raises an Exception it reports the file as "<unknown>" even though I am passing it the name of a template, e.g:

```
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'x'.
```

The following code replicates the issue:

```
#!/usr/bin/env python3

import jinja2, traceback

template = {
  'Default': '{% Test x'
}

try:
  env = jinja2.Environment(loader=jinja2.DictLoader(template))
  rtemplate = env.get_template('Default')
  content = rtemplate.render()

except Exception:
  traceback.print_exc()
```

The full trackback is as follows:

```
Traceback (most recent call last):
  File "/home/cmason3/./test.py", line 11, in <module>
    rtemplate = env.get_template('Default')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmason3/bin/python3/lib/python3.11/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmason3/bin/python3/lib/python3.11/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmason3/bin/python3/lib/python3.11/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmason3/bin/python3/lib/python3.11/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/cmason3/bin/python3/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'Test'.
```

As we are passing the name of the template into `get_template()` then it knows the name of the template - the same is true if it includes another template from the dict - is it possible to actually report the template name (instead of "<unknown>" - maybe "<actual template name>") when using the DictLoader? When I include multiple templates it gets quite confusing to understand which template the error occurred in - the line numbers seem to be correct once I work out what template it is referring to.

Environment:

- Python version: 3.11.2
- Jinja version: 3.1.4

**Comment by davidism** [comment]
The value in the traceback is the name of a file, not the name of a template. There's no file backing templates for `DictLoader`, only template names.

**Comment by cmason3** [comment]
Is there no way to add the name of the template into the traceback else the user has no idea which one of their templates caused the error?

**Comment by cmason3** [comment]
If this isn’t the right way - is there currently any way that I can determine what template in the dictionary caused an exception when using a DictLoader?

**Comment by cmason3** [comment]
It looks like it is available in `jinja2.TemplateError.name` and the line number in `jinja2.TemplateError.lineno` - I assume this is stable?
