### ISSUE TITLE
macro variable referenced before assignment

### ISSUE THREAD

**Issue by azulus** [pallets/jinja#278]
Instantiating a variable from within a loop in a macro breaks if the same variable name is used outside of the macro:

``` python
from jinja2 import Template

template = """
{% set i = 1 %}
{% macro test() %}
    {% for i in range(0, 10) %}{{ i }}{% endfor %}
{% endmacro %}{{ test() }}
"""

print Template(template).render()
```

Output from 2.7:

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    print Template(template).render()
  File "/Library/Python/2.7/site-packages/Jinja2-2.7.2_devdev_20131111-py2.7.egg/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Python/2.7/site-packages/Jinja2-2.7.2_devdev_20131111-py2.7.egg/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 5, in top-level template code
  File "<template>", line 3, in template
UnboundLocalError: local variable 'l_i' referenced before assignment
```

And 2.8 dev:

```
[ test_macros ]$ python test.py 
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    print template.render()
  File "/Library/Python/2.7/site-packages/Jinja2-2.8_devdev_20131111-py2.7.egg/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Python/2.7/site-packages/Jinja2-2.8_devdev_20131111-py2.7.egg/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 5, in top-level template code
  File "<template>", line 3, in template
UnboundLocalError: local variable 'l_i' referenced before assignment
```

This also breaks with nested macros:

``` python
from jinja2 import Template

template = """
{% macro outer() %}
    {% set i = 1 %}
    {% macro test() %}
        {% for i in range(0, 10) %}{{ i }}{% endfor %}
    {% endmacro %}{{ test() }}
{% endmacro %}{{ outer() }}
"""

print Template(template).render()
```

and works as expected if you only reference the variable:

``` python
from jinja2 import Template

template = """
{% set i = 1 %}
{% macro test() %}
    {{ i }}
{% endmacro %}{{ test() }}
"""

print Template(template).render()
```

**Comment by mitsuhiko** [comment]
Fixed in #637
