### ISSUE TITLE
Convert large json file to html  raises "MemoryError"

### ISSUE THREAD

**Issue by vincentping** [pallets/jinja#372]
I'm using jinja 2.7.3 to convert test log (json file) to html,  the template using is pretty simple:

``` html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<head>
    <meta charset="UTF-8" />
 <title></title>
</head>
<body>
{%- for item in  logs -%}
<table>
    <tr>
    <td width="80"><nobr>APDU:</nobr></td>
    <td>{{ item['apdu'] }}</td>
    </tr>
    <tr>
    <td width="80"><nobr>Response:</nobr></td>
    <td> {{ item['aresp'] }}</td>
    </tr>
    <tr>
    <td width="80"><nobr>ExpectData:</nobr></td>
    <td>{{ item.get('expdata','None') }} </td>
    </tr>
    <tr>
    <td width="80"><nobr>ExpectStatus:</nobr></td>
    <td>{{ item.get('expsw','None') }}  </td>
    </tr>
    <tr>
    <td width="80"><nobr>ErrorInfo:</nobr></td>
    <td>{% if 'errorinfo' in item -%}<font color='red'>Error!</font> {{ item['errorinfo'] }}{%- else %}None{%- endif%}</td>
    </tr>
</table>
<hr>
{% endfor %}
</body>
</html>
```

I use a simple script to convert it:

``` python
import json
import jinja2

template_dir =r'E:\test'
env=jinja2.Environment(loader=jinja2.FileSystemLoader(template_dir))

logfile = r'.\a.json'
with open(logfile, 'r') as fi:
    data = json.load(fi)

template = env.get_template('readlog.htm')
templateVars = {"logs": data["logitem"]}

with open('b.html','w') as fo:
    fo.write(template.render(templateVars))

```

When the log file is large near 30M, the template.render(templateVars) raise "MemoryError", I tried some other log files smaller, such 2-10M, the script runs fine.

```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    fo.write(template.render(templateVars))
  File "D:\python27\lib\site-packages\jinja2\environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\python27\lib\site-packages\jinja2\environment.py", line 736, in handle_exception
    traceback = _make_traceback(exc_info, source_hint)
  File "D:\python27\lib\site-packages\jinja2\debug.py", line 140, in make_traceback
    return translate_exception(exc_info, initial_skip)
  File "D:\python27\lib\site-packages\jinja2\debug.py", line 193, in translate_exception
    reraise(exc_info[0], exc_info[1], exc_info[2])
  File "D:\python27\lib\site-packages\jinja2\environment.py", line 966, in render
    return concat(self.root_render_func(self.new_context(vars)))
MemoryError
```

My environnement is:
Windows XP
Python 2.7.8
Jinja2 : 2.7.3

**Comment by mitsuhiko** [comment]
Also for future reference: Jinja can iteratively render templates with the stream system.
