### ISSUE TITLE
AttributeError: 'int' object has no attribute 'iter_fields'

### ISSUE THREAD

**Issue by jacebrowning** [pallets/jinja#396]
I installed `cookiecutter` using `pip` for Python 3.4 which uses Jinja2 version `2.7.3`. I get a traceback inside Jinja2 running `cookiecutter` with basic options:

```
Traceback (most recent call last):
  File "/opt/boxen/homebrew/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/bin/cookiecutter", line 9, in <module>
    load_entry_point('cookiecutter==0.9.0', 'console_scripts', 'cookiecutter')()
  File "/opt/boxen/homebrew/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cookiecutter/main.py", line 169, in main
    cookiecutter(args.input_dir, args.checkout, args.no_input)
  File "/opt/boxen/homebrew/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cookiecutter/main.py", line 100, in cookiecutter
    context['cookiecutter'] = prompt_for_config(context, no_input)
  File "/opt/boxen/homebrew/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cookiecutter/prompt.py", line 29, in prompt_for_config
    val = env.from_string(raw).render(cookiecutter=cookiecutter_dict)
  File "/opt/boxen/homebrew/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/environment.py", line 841, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/opt/boxen/homebrew/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/environment.py", line 542, in compile
    source = optimize(source, self)
  File "/opt/boxen/homebrew/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/optimizer.py", line 27, in optimize
    return optimizer.visit(node)
  File "/opt/boxen/homebrew/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/visitor.py", line 39, in visit
    return self.generic_visit(node, *args, **kwargs)
  File "/opt/boxen/homebrew/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/visitor.py", line 59, in generic_visit
    for field, old_value in node.iter_fields():
AttributeError: 'int' object has no attribute 'iter_fields'
```

**Comment by joshfriend** [comment]
I'm experiencing the same error (python 2.7.9/3.4.2 with `jinja==2.7.3`).

**Comment by untitaker** [comment]
This is the first time I hear of such a bug. How can you be sure that this is Jinja's problem?

**Comment by jacebrowning** [comment]
@untitaker I'm not certain this is a `jinja2` problem, but the exception occurs half a dozen calls into `jinja2`'s stack. I've submitted the same issue to `cookiecutter` for them to investigate as well. Maybe they're calling an API incorrectly.

**Comment by jacebrowning** [comment]
This was fixed in `cookiecutter` by casting each object to a string before calling `<Environment>.from_string()`: 

https://github.com/jacebrowning/cookiecutter/blob/05cd9b353793d382bdd1c689f8d705c723352624/cookiecutter/prompt.py#L29-30

Therefore, this **was** a `cookiecutter` bug, but _maybe_, `jinja2` should fail sooner if `from_string` is passed a non-string.

Feel free to close.

**Comment by ThiefMaster** [comment]
@jacebrowning  As the creator of the issue you should be able to close it on your own.
