### ISSUE TITLE
Multiple Custom Tests in Condition Not Parsed Correctly

### ISSUE THREAD

**Issue by codyaray** [pallets/jinja#401]
It appears that conditions with multiple custom tests aren't parsed as a user would expect. For example, if you define an `is_matching` test as follows

```
def is_matching(string, pattern):
  return match(pattern, string) is not None
```

then the following custom test should succeed.

```
{% if 'us-west-1' is matching '(us-east-1|ap-northeast-1)' or 'stage' is matching '(dev|stage)' %}
  ...
{% endif %}
```

should be met but its not.

Here's a [runnable example](http://runnable.com/VMlOjoR7mw4_m0cu) that demonstrates the issue. 

```
'us-west-1' == 'us-east-1' or 'stage' is matching '(dev|stage)'
  => True # should be True

'stage' is matching '(dev|stage)' or 'us-west-1' == 'us-east-1'
  => True # should be True

'us-west-1' is matching '(us-east-1|ap-northeast-1)' or 'stage' is matching '(dev|stage)'
  => False # should be True
```

As you can see, the custom test works if there is only one in the condition. However, it appears that the second custom test condition (following the `or`) is never executed if the first isn't met. (This can be seen in the output of the runnable, where I've printed the arguments to the custom test function for each invocation.)

I suspect that this is due to the expected order of operations not being respected. For example

```
'stage' is matching '(dev|stage)' and 'us-west-1' is matching '(us-east-1|ap-northeast-1)'
```

results in an exception for my custom test:

```
Traceback (most recent call last):
  File "/Users/codyaray/dev/brighttag/ops/management/haproxygen/bug.py", line 20, in <module>
    print template.render()
  File "/Users/codyaray/.virtualenv/haproxygen/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/codyaray/.virtualenv/haproxygen/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/codyaray/dev/brighttag/ops/management/haproxygen/templates/buggy.txt", line 18, in top-level template code
    => {{ 'stage' is matching '(dev|stage)' and 'us-west-1' is matching '(us-east-1|ap-northeast-1)' }} # should be False
  File "/Users/codyaray/dev/brighttag/ops/management/haproxygen/bug.py", line 13, in is_matching
    return match(pattern, string) is not None
  File "/Users/codyaray/.virtualenv/haproxygen/lib/python2.7/re.py", line 137, in match
    return _compile(pattern, flags).match(string)
  File "/Users/codyaray/.virtualenv/haproxygen/lib/python2.7/re.py", line 238, in _compile
    raise TypeError, "first argument must be string or compiled pattern"
TypeError: first argument must be string or compiled pattern
```

Printing the args to the custom function shows that it was called as `is_matching('stage', False)` instead of the expected `is_matching('stage', '(dev|stage)')` invocation. It seems like the second condition is actually tested here, resulting in False, which is then `and`ed with the search string '(dev|stage)' which yields a logical False to the next invocation of the custom test function.

**Comment by sekimura** [comment]
Here's a simplified test to reproduce this case.

```
    def test_custom_tests(self):
        env = Environment()
        env.tests['more_than'] = lambda x, y: x > y
        tmpl = env.from_string("{{ foo is more_than 1 or bar is more_than 1 }}")
        assert tmpl.render(foo=0, bar=2) == 'True'
```

This template will be parsed as:
```
Template(body=[Output(nodes=[Test(node=Name(name='foo', ctx='load'), name='more_than', args=[Or(left=Const(value=1), right=Test(node=Name(name='bar', ctx='load'), name='more_than', args=[Const(value=1)], kwargs=[], dyn_args=None, dyn_kwargs=None))], kwargs=[], dyn_args=None, dyn_kwargs=None)])])
```

Note: the position of "Or" and first args param. It's basically a equivalent of {{ foo is more_than(1 or bar is more_than(1)) }}

It's fine if tests get args with parenthesis .

```
        tmpl = env.from_string("{{ foo is more_than(1) or bar is more_than(1) }}")
        assert tmpl.render(foo=0, bar=2) == 'True'
```

which generates

```
Template(body=[Output(nodes=[Or(left=Test(node=Name(name='foo', ctx='load'), name='more_than', args=[Const(value=1)], kwargs=[], dyn_args=None, dyn_kwargs=None), right=Test(node=Name(name='bar', ctx='load'), name='more_than', args=[Const(value=1)], kwargs=[], dyn_args=None, dyn_kwargs=None))])])
```

**Comment by jmedinar** [comment]
Might not be the best answer but it worked! 

```python
{% if grains['id'] == 'id1' or
   grains['id'] == 'id2' or
   grains['id'] == 'id3'
%}
```

Although I was looking for something like 

```python
{% if grains['id'] == 'id*' %}
```

**Comment by mitsuhiko** [comment]
This turns out to be priorities in Jinja2.

Currently

```
'us-west-1' is matching '(us-east-1|ap-northeast-1)' or 'stage' is matching '(dev|stage)'
```

Means

```
'us-west-1' is matching ('(us-east-1|ap-northeast-1)' or ('stage' is matching '(dev|stage)'))
```

Instead of what makes more sense

```
('us-west-1' is matching '(us-east-1|ap-northeast-1)') or ('stage' is matching '(dev|stage)')
```

Need to figure out how to improve this.

**Comment by codyaray** [comment]
Thanks @mitsuhiko!
