### ISSUE TITLE
UndefinedError on render not helpful.

### ISSUE THREAD

**Issue by Rory-Finnegan** [pallets/jinja#464]
Rendering a template with a dict that is missing a value returns an undefined error, which it should when using `StrictUndefined()`, but always returns None rather than the expected key name in the error message. Obviously, this isn't a helpful error message.

```
bpython version 0.14.2 on top of Python 3.4.3 /Users/rory/repos/jinja2/venv/bin/python3.4
>>> import jinja2
>>> from jinja2 import Template, StrictUndefined
>>> jinja_template = Template("{{ foo }}: {{ bar }}")
>>> jinja_template.environment.undefined = StrictUndefined()
>>> jinja_template.render({"foo": 3, "bar": 4})
'3: 4'
>>> jinja_template.render({"foo": 3})
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/rory/repos/jinja2/venv/lib/python3.4/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/rory/repos/jinja2/venv/lib/python3.4/site-packages/jinja2/environment.py", line 742, in handle_exc
eption
    reraise(exc_type, exc_value, tb)
  File "/Users/rory/repos/jinja2/venv/lib/python3.4/site-packages/jinja2/_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in <module>
  File "/Users/rory/repos/jinja2/venv/lib/python3.4/site-packages/jinja2/runtime.py", line 154, in resolve
    return self.environment.undefined(name=key)
jinja2.exceptions.UndefinedError: None is undefined
```

**Comment by mitsuhiko** [comment]
This is a usage error. It should be `undefined = StrictUndefined`.
