### ISSUE TITLE
jinja2 2.6 unittest errors on windows

### ISSUE THREAD

**Issue by mindw** [pallets/jinja#60]
On WinXP SP2 using Python 2.7.2 using the following command line
> python -m unittest jinja2.testsuite.suite

gives the below errors:
======================================================================
ERROR: test_byte_compilation (jinja2.testsuite.loader.ModuleLoaderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\jinja2\testsuite\__init__.py", line 51, in tearDown
    self.teardown()
  File "C:\Python27\lib\site-packages\jinja2\testsuite\loader.py", line 124, in teardown
    os.remove(self.archive)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\windows\\temp\\tmpoyofll.zip'

======================================================================
ERROR: test_deflated_zip_compile (jinja2.testsuite.loader.ModuleLoaderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\jinja2\testsuite\__init__.py", line 51, in tearDown
    self.teardown()
  File "C:\Python27\lib\site-packages\jinja2\testsuite\loader.py", line 124, in teardown
    os.remove(self.archive)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\windows\\temp\\tmps9be2f.zip'

======================================================================
ERROR: test_log (jinja2.testsuite.loader.ModuleLoaderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\jinja2\testsuite\__init__.py", line 51, in tearDown
    self.teardown()
  File "C:\Python27\lib\site-packages\jinja2\testsuite\loader.py", line 124, in teardown
    os.remove(self.archive)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\windows\\temp\\tmpe0vzue.zip'

======================================================================
ERROR: test_stored_zip_compile (jinja2.testsuite.loader.ModuleLoaderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\jinja2\testsuite\__init__.py", line 51, in tearDown
    self.teardown()
  File "C:\Python27\lib\site-packages\jinja2\testsuite\loader.py", line 124, in teardown
    os.remove(self.archive)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\windows\\temp\\tmpxo2zko.zip'

======================================================================
ERROR: test_weak_references (jinja2.testsuite.loader.ModuleLoaderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\jinja2\testsuite\__init__.py", line 51, in tearDown
    self.teardown()
  File "C:\Python27\lib\site-packages\jinja2\testsuite\loader.py", line 124, in teardown
    os.remove(self.archive)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\windows\\temp\\tmpf8_oab.zip'

----------------------------------------------------------------------
Ran 266 tests in 1.000s

FAILED (errors=5)

**Comment by jeffwidman** [comment]
Since we're now on Jinja 2.8, I'm going to close this. If you still experience these issues with the latest version, please comment and we can reopen.
