### ISSUE TITLE
ImportError: cannot import name EscapeFormatter

### ISSUE THREAD

**Issue by alexsv** [pallets/jinja#638]
Hi, I'm getting now
```
ImportError: cannot import name EscapeFormatter
Exception occurred:
  File "/home/jenkins/workspace/eggs/Jinja2-2.8.1-py2.7.egg/jinja2/sandbox.py", line 25, in <module>
    from markupsafe import EscapeFormatter
ImportError: cannot import name EscapeFormatter
```
Should some min version for Markupsafe be specified in setup.py?

**Comment by ashishpatil-TML** [comment]
Was getting the same issue post installation of Airflow.
Below is the error,

/usr/lib64/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "/usr/bin/airflow", line 27, in <module>
    args.func(args)
  File "/usr/lib/python2.7/site-packages/airflow/bin/cli.py", line 678, in webserver
    app = cached_app(conf)
  File "/usr/lib/python2.7/site-packages/airflow/www/app.py", line 161, in cached_app
    app = create_app(config)
  File "/usr/lib/python2.7/site-packages/airflow/www/app.py", line 59, in create_app
    from airflow.www import views
  File "/usr/lib/python2.7/site-packages/airflow/www/views.py", line 49, in <module>
    from jinja2.sandbox import ImmutableSandboxedEnvironment
  File "/usr/lib64/python2.7/site-packages/jinja2/sandbox.py", line 25, in <module>
    from markupsafe import EscapeFormatter
ImportError: cannot import name EscapeFormatter


Workaround:
As it seems to be python package related issue, tried to check if the package markupsafe exists at path 
/usr/lib64/python2.7/site-packages/

It does exists, but while importing it as from markupsafe import EscapeFormatter in python shell, it was giving same error. Looks that files are corrupt may be.

so , re-installing package and importing again, helped me.

sudo pip uninstall markupsafe
sudo pip install markupsafe

After this, from markupsafe import EscapeFormatter worked well in python shell.

Now start Airflow webserver and it works fine.
airflow webserver -p 8080
