### ISSUE TITLE
Error when use field of object or dictionary in trans block

### ISSUE THREAD

**Issue by aolefira** [pallets/jinja#679]
## Expected Behavior
{% trans %}{{ obj_or_dict.field_name }}{% endtrans %}
should display field_name of obj_or_dict

## Actual Behavior
Got an exception

## Template Code
```jinja
{% trans %}{{ obj_or_dict.field_name }}{% endtrans %}
```

## Full Traceback
```
strace: Traceback (most recent call last):
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/pyramid/router.py", line 145, in handle_request
    view_name
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/pyramid/config/views.py", line 244, in _secured_view
    return view(context, request)
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/pyramid/config/views.py", line 377, in rendered_view
    context)
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/pyramid/renderers.py", line 450, in render_view
    return self.render_to_response(response, system, request=request)
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/pyramid/renderers.py", line 473, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/pyramid/renderers.py", line 469, in render
    result = renderer(value, system_values)
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/pyramid_jinja2/__init__.py", line 264, in __call__
    template = self.template_loader()
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/pyramid_jinja2/__init__.py", line 283, in template_loader
    return self.environment.get_template(name)
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/jinja2/environment.py", line 786, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/jinja2/environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/andrewolefira/work/plarin-3.5.1/vkad/vkad/templates/account/account_ga.html", line 2, in template
    {% trans %}{{ obj_or_dict.field_name }}{% endtrans %}
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/jinja2/environment.py", line 470, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/jinja2/parser.py", line 897, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/jinja2/parser.py", line 879, in subparse
    rv = self.parse_statement()
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/jinja2/parser.py", line 128, in parse_statement
    return ext(self)
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/jinja2/ext.py", line 264, in parse
    singular_names, singular = self._parse_block(parser, True)
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/jinja2/ext.py", line 322, in _parse_block
    parser.stream.expect('variable_end')
  File "/Users/andrewolefira/.pyenv/versions/plarin-3.6.0/lib/python3.6/site-packages/jinja2/lexer.py", line 374, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '.'
```

## Your Environment
* Python version: 3.6.0
* Jinja version: 2.8

**Comment by ThiefMaster** [comment]
That was never possible. For anything but plain vars you need `{% trans foo=obj.attr %}`
