### ISSUE TITLE
Jina2 Async - Error when loop is already running

### ISSUE THREAD

**Issue by TomIsPrettyCool** [pallets/jinja#696]
## Expected Behavior
When rendering a template when running on an existing loop, Jinja2 should render the template asynchronously. It should use the existing, running event loop.

## Actual Behavior
Jinja2 tries to start the event loop anyway, it doesn't seem to check wether the event loop is already running: (asyncsupport.py line 77)
```
loop = asyncio.get_event_loop()
return loop.run_until_complete(self.render_async(*args, **kwargs))
```

Im not sure if this is because I'm running on uvloop, I will double check with the normal asyncio event loop soon.

Could we just check if the loop is already running?
## Full Traceback
```
2017-03-25 22:37:09,051: INFO: Goin' Fast @ http://127.0.0.1:8000
2017-03-25 22:37:09,056: INFO: Starting worker [2159]
2017-03-25 22:37:12,085: ERROR: Traceback (most recent call last):
  File "/Users/tom/.virtualenvs/async_personal/lib/python3.6/site-packages/sanic/app.py", line 391, in handle_request
    response = await response
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/Users/tom/python/async_personal/personal/home/views.py", line 14, in home
    rendered_template = await home_template.render()
  File "/Users/tom/.virtualenvs/async_personal/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 78, in render
    return loop.run_until_complete(self.render_async(*args, **kwargs))
  File "uvloop/loop.pyx", line 1198, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25480)
  File "uvloop/loop.pyx", line 1191, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25324)
  File "uvloop/loop.pyx", line 1100, in uvloop.loop.Loop.run_forever (uvloop/loop.c:24056)
  File "uvloop/loop.pyx", line 355, in uvloop.loop.Loop._run (uvloop/loop.c:11384)
RuntimeError: this event loop is already running.
```
For convenience I printed the loop object and got: `<uvloop.Loop running=True closed=False debug=True>`

## Your Environment
* Python version: 3.6 MacOS with the UVLoop event loop
* Jinja version: 2.9.5

**Comment by ThiefMaster** [comment]
Does using `render_async()` directly do what you want? I think `render` is always supposed to be sync.

**Comment by TomIsPrettyCool** [comment]
It does, I feel silly now.

To avoid this in future could the `render_async` method be added to the documentation under [Async Support?](http://jinja.pocoo.org/docs/2.9/api/#async-support) 

Its not immediately obvious you need to call a different method.
