### ISSUE TITLE
Truncate filter crashes if input isn't a string

### ISSUE THREAD

**Issue by xychix** [pallets/jinja#706]
## Expected Behavior
Add a check for 'if not string' in filter 'truncate'

## Actual Behavior
crashes on 'len(s)' if item is None or int (not string)

## Template Code
```jinja
{% for item in  data.list %}item is{{ item | truncate(4) }}{% endfor %}
```

## Full Traceback
```pytb
>>> import jinja2
>>> data['list'] = ['longAAAAAAAAAAA','shortAA',123456789,None]
>>> templ = "{% for item in  data.list %}item is{{ item | truncate(4) }}{% endfor %}"
>>> jinja2.Environment().from_string(templ).render(data=data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mark/.local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/mark/.local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/home/mark/.local/lib/python2.7/site-packages/jinja2/filters.py", line 476, in do_truncate
    if len(s) <= length:
TypeError: object of type 'int' has no len()
```

## Your Environment
* Python version: Python 2.7.12+
* Jinja version: Jinja2 (2.8)

**Comment by ThiefMaster** [comment]
Why would the filter work on something that's not a string? Doesn't make much sense IMO...

**Comment by xychix** [comment]
crashing wouldn't be the best behaviour...
Just return the input value, or return an empty string, or cast to string... all fine by me but not crashing hard :)

**Comment by ThiefMaster** [comment]
IMO an exception makes it clear that something is going wrong

**Comment by xychix** [comment]
my bad, this can be easy solved by changing the template to:

```
{% for item in  data.list %}item is{{ item | string | truncate(4) }}{% endfor %}
```

I'll close this issue. My apologies
