### ISSUE TITLE
return dict instead of string in extension template tag?

### ISSUE THREAD

**Issue by AlJohri** [pallets/jinja#714]
## Expected Behavior
I expect to be able to return a dict instead of a string from an extension template tag. I am trying to create `paragraph` and `sentence` template tags that can be nested. I expect to be able to look at the type of the output and combine the dictionaries accordingly.

Basically, I want the entire template to return a big nested json of sentences, paragraphs, and other types of tags I have yet to define. I'm trying to create something that interacts with this: https://github.com/simplenlg/simplenlg/wiki/Section-XIV-%E2%80%93-Beyond-sentences

## Actual Behavior
It raises a TypeError.

## Template Code
```python
import re
import json
import jinja2
import requests
from jinja2 import Template, Environment
from jinja2 import nodes
from jinja2.ext import Extension
# from htmlmin import minify

def _fix_sentence_spacing(x):
    return re.sub("\s\s+", " ", x).replace(" .", ".").replace(" ;", ";").replace(" ,", ",").strip().capitalize()

def _fix_paragraph_spacing(x):
    # return minify(x).strip()
    return x.strip()

class ParagraphExtension(Extension):
    tags = set(['paragraph'])

    def parse(self, parser):
        lineno = next(parser.stream).lineno
        ctx_ref = nodes.ContextReference()
        body = parser.parse_statements(['name:endparagraph'], drop_needle=True)
        node = self.call_method('_render_paragraph', [ctx_ref], lineno=lineno)
        return nodes.CallBlock(node, [], [], body).set_lineno(lineno)

    def _render_paragraph(self, context, caller):
        text = caller()
        text = _fix_paragraph_spacing(text)
        return nodes.Dict({"text": text})

class SentenceExtension(Extension):
    tags = set(['sentence'])

    def parse(self, parser):
        lineno = next(parser.stream).lineno
        ctx_ref = nodes.ContextReference()
        body = parser.parse_statements(['name:endsentence'], drop_needle=True)
        node = self.call_method('_render_sentence', [ctx_ref], lineno=lineno)
        return nodes.CallBlock(node, [], [], body).set_lineno(lineno)

    def _render_sentence(self, context, caller):
        text = caller()
        text = _fix_sentence_spacing(text)
        # return text
        return nodes.Dict({"text": text})

class SimpleNLGTemplate(Template):

    def render(self, **kwargs):
        """
        Ensures that each item yielded is a dict or whitespace. Combines all dicts
        into a list and returns it.
        """
        elements = []
        for x in self.generate(**kwargs):
            if isinstance(x, str) and x.strip() == "":
                pass
            elif not isinstance(x, nodes.Dict):
                raise TypeError(f"Template returned non-dict value. Value was: {x}")
            else:
                elements.append(x)
        return {"elements": elements}

env = Environment(extensions=[ParagraphExtension, SentenceExtension])

env.template_class = SimpleNLGTemplate

x = """
{% sentence %}
    This is a sentence
    of text.
{% endsentence %}
""".strip()

y = """
{% paragraph %}
    This is outside the sentence.
{% endparagraph %}
""".strip()

z = """
{% paragraph %}
    This is outside the sentence.
    {% sentence %}
        This is a sentence
        of text.
    {% endsentence %}
{% endparagraph %}
""".strip()

# works
template = env.from_string(x)
output = template.render()
print(output)

# works
template = env.from_string(y)
output = template.render()
print(output)

# fails
template = env.from_string(z)
output = template.render()
print(output)
```

## Full Traceback
```pytb
Traceback (most recent call last):
  File "testjinja2.py", line 162, in <module>
    y = template.render(candidate1='Bernie Sanders', candidate2='Hilary Clinton', make_past=True)
  File "testjinja2.py", line 73, in render
    for x in self.generate(**kwargs):
  File "/Users/johria/.virtualenvs/generic/lib/python3.6/site-packages/jinja2/environment.py", line 1045, in generate
    yield self.environment.handle_exception(exc_info, True)
  File "/Users/johria/.virtualenvs/generic/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/johria/.virtualenvs/generic/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "testjinja2.py", line 48, in _render_paragraph
    text = caller()
  File "/Users/johria/.virtualenvs/generic/lib/python3.6/site-packages/jinja2/runtime.py", line 554, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 5, in template
TypeError: sequence item 1: expected str instance, Dict found
```

## Your Environment
* Python version: 3.6.0
* Jinja version: 2.9.6

**Comment by davidism** [comment]
Closing as there's been no development and this seems more like an implementation question rather than a bug. I don't know what the right answer for your use case is, but it seems like you're trying to do too much work in the template. You might be able to use `Assign` and the new `DerrivedContextReference` to store data, or if you need to introspect the AST, it might be time for a custom `CodeGenerator` instead.
