### ISSUE TITLE
builtins.TypeError: Can't compile non template nodes

### ISSUE THREAD

**Issue by umrashrf** [pallets/jinja#753]
## Expected Behavior
Template should be replaced with arguments.

## Actual Behavior
Exception

## Template Code
```jinja
http://jinja.pocoo.org/docs/2.9/intro/#basic-api-usage
```

## Full Traceback
```pytb
Unhandled Error
Traceback (most recent call last):
  File "/home/username/.pyenv/versions/project-name/lib/python3.6/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/home/username/.pyenv/versions/project-name/lib/python3.6/site-packages/twisted/web/http.py", line 1964, in lineReceived
    self.allContentReceived()
  File "/home/username/.pyenv/versions/project-name/lib/python3.6/site-packages/twisted/web/http.py", line 2059, in allContentReceived
    req.requestReceived(command, path, version)
  File "/home/username/.pyenv/versions/project-name/lib/python3.6/site-packages/twisted/web/http.py", line 869, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/home/username/.pyenv/versions/project-name/lib/python3.6/site-packages/twisted/web/server.py", line 184, in process
    self.render(resrc)
  File "/home/username/.pyenv/versions/project-name/lib/python3.6/site-packages/twisted/web/server.py", line 235, in render
    body = resrc.render(self)
  File "/home/username/.pyenv/versions/project-name/lib/python3.6/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/username/Development/edu/retriever/pkg/server/index.py", line 21, in render_GET
    tpl = Template(content)
  File "/home/username/.pyenv/versions/project-name/lib/python3.6/site-packages/jinja2/environment.py", line 945, in __new__
    return env.from_string(source, template_class=cls)
  File "/home/username/.pyenv/versions/project-name/lib/python3.6/site-packages/jinja2/environment.py", line 880, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/home/username/.pyenv/versions/project-name/lib/python3.6/site-packages/jinja2/environment.py", line 581, in compile
    defer_init=defer_init)
  File "/home/username/.pyenv/versions/project-name/lib/python3.6/site-packages/jinja2/environment.py", line 543, in _generate
    optimized=self.optimized)
  File "/home/username/.pyenv/versions/project-name/lib/python3.6/site-packages/jinja2/compiler.py", line 78, in generate
    raise TypeError('Can\'t compile non template nodes')
builtins.TypeError: Can't compile non template nodes
```

## Your Environment
* Python version: 3.6.0
* Jinja version: 2.9.6

**Comment by davidism** [comment]
From your traceback, `tpl = Template(content)`, `content` is not a string or `Template` instance. The intro code you linked works fine.

**Comment by umrashrf** [comment]
@davidism the same code works when I switch to PY2.

In PY3 the string type is actually bytes (b"") so that could be the issue.

**Comment by davidism** [comment]
I can't reproduce your issue on Python 3.

**Comment by umrashrf** [comment]
@davidism what is your PY3 version?

**Comment by davidism** [comment]
All supported Python 3 versions: 3.3 - 3.6.

**Comment by umrashrf** [comment]
@davidism Okay the issue was I was encoding content to utf-8 before passing it to Template(). Now I am encoding the result of ```tpl.render(**kwargs).encode("utf-8")``` and it works.
