### ISSUE TITLE
pip install --user jinja2 fails, I did find a workaround

### ISSUE THREAD

**Issue by dschere** [pallets/jinja#774]
## Expected Behavior
 pip install  --user "jinja2" should install

## Actual Behavior

```
Using cached MarkupSafe-1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-GY7CL1/MarkupSafe/setup.py", line 132, in <module>
        try_building_extension()
      File "/tmp/pip-build-GY7CL1/MarkupSafe/setup.py", line 111, in try_building_extension
        run_setup(True)
      File "/tmp/pip-build-GY7CL1/MarkupSafe/setup.py", line 105, in run_setup
        features=features,
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 270, in __init__
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 706, in iter_entry_points
        entries = dist.get_entry_map(group)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2577, in get_entry_map
        self._get_metadata('entry_points.txt'), self
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2307, in parse_map
        for group, lines in data:
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2878, in split_sections
        for line in yield_lines(s):
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2174, in yield_lines
        for ss in strs:
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2503, in _get_metadata
        for line in self.get_metadata_lines(name):
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1477, in get_metadata_lines
        return yield_lines(self.get_metadata(name))
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1469, in get_metadata
        return self._get(self._fn(self.egg_info, name))
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1580, in _get
        with open(path, 'rb') as stream:
    IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/WebError-0.10.3-py2.7.egg/EGG-INFO/entry_points.txt'
```

work around

```
sudo chown myusername:myusername /usr/local/lib/python2.7/dist-packages/WebError-0.10.3-py2.7.egg/EGG-INFO/entry_points.txt
```

**Comment by davidism** [comment]
I can't reproduce your issue. Regardless, this would be an issue with pip, not Jinja.
