### ISSUE TITLE
[BUG] Bad file descriptor error when using with a thread pool greater than 1

### ISSUE THREAD

**Issue by bitsofdave** [pallets/jinja#791]
## Expected Behavior
Render templates without error when running in a thread pool greater than 1.

## Actual Behavior
Results in a `OSError: [Errno 9] Bad file descriptor` error when trying to perform `os.stat(filename).st_mtime`. Some runs do complete without error, but it's rare.

## Template Code
This creates a thread pool of size 2 and tries to print 100 numbers. 

In `test_template.html`:
```jinja
Run #{{ number }}
```
In `test_jinja.py`:
```pytb
import os
import jinja2
from multiprocessing.dummy import Pool

def thread(param):
    filename = 'test_template.html'

    context = {
        'number': param
    }

    text = jinja2.Environment(
        loader=jinja2.FileSystemLoader('./')
    ).get_template(filename).render(context)

    print(text)

def main():
    pool = Pool(2)
    results = pool.map(thread, range(100))
    pool.close()
    pool.join()

main()
```
Running via:
```bash
python test_jinja.py
```

## Full Traceback
```pytb
$ python test_jinja.py 
Run #0
Run #39
Run #1
Run #40
Run #2
Run #41
Run #3
Run #42
Run #4
Run #43
Run #5
Run #6
Run #44
Run #7
Run #45
Run #8
Run #9
Run #10
Run #78
Run #11
Run #91
Run #92
Run #93
Run #94
Run #95
Run #96
Run #97
Run #98
Run #99
Traceback (most recent call last):
  File "test_jinja.py", line 24, in <module>
    main()
  File "test_jinja.py", line 20, in main
    results = pool.map(thread, range(100))
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "test_jinja.py", line 14, in thread
    ).get_template(filename).render(context)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/usr/local/lib/python3.6/site-packages/jinja2/loaders.py", line 179, in get_source
    mtime = path.getmtime(filename)
  File "/usr/local/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 9] Bad file descriptor: './test_template.html'
```

## Your Environment
* Python version: 3.6.3
* Jinja version: 2.8.1

**Comment by ngr** [comment]
Can't reproduce with Python `3.6.3` or `3.6.5` (latest stable at the moment). `Jinja2` versions:  `2.8.1` or `2.10`. Tried running up to 100,000 iterations with different pool size (up to 25).

**Comment by mitsuhiko** [comment]
This sounds like it runs into ulimits. This seems to be a configuration error. Disabling autoreload should also work around this.

**Comment by bitsofdave** [comment]
I'm also unable to reproduce this now. Thanks for looking into it.

**Comment by strigazi** [comment]
@mitsuhiko I'm not sure how to fix this, can you elaborate a bit. Thanks!

**Comment by mitsuhiko** [comment]
I cannot tell. I assume the likely reason one might see this is some server doing weird things with fork. You would need to describe your setup but generally unlikely to be jinja related. You might just see it there because in reload mode (which you can just turn off) jinja will stat a lot.
