### ISSUE TITLE
Non-generic OS path detection.

### ISSUE THREAD

**Issue by frndlytm** [pallets/jinja#856]
## Code
The error is introduced in the make() call by get_template()
```
from os.path import join

class ModelFactory:
    def __init__(self, environment, flavor, fieldfactory):
        self.environment = environment
        self.flavor = flavor
        self.fieldfactory = fieldfactory

    def make(self, database, schema, name, fields=[], constraints=dict()):
        # get the template by flavor...
        template = self.environment.get_template(join(self.flavor,'create.j2'))

        # map a serialized format onto the fields...
        fields = map(lambda x: self.fieldfactory.make(x), fields)

        # build the table.
        return Model(template, database, schema, name, fields, constraints)

```
The environment uses a FileSystemLoader on os.path.join(os.path.dirname(__file__), 'templates') in my settings file. 

## Expected Behavior
This snippet should detect the template 'mssql\create.j2' in Windows.

## Actual Behavior
Running list_templates() on the environment detects 'mssql/create.j2' like a unix path, but raises a TemplateNotFoundError for 'mssql\create.j2'. When I change my code to below, it detects the template:
```
        template = self.environment.get_template(self.flavor+'/create.j2')
```
It seems strange not to support generic OS functionality, and seems like FileSystemLoader normalizes all environments down to a list of Unix paths. Consider extending to build OS-specific paths.

## Traceback
```pytb
Traceback (most recent call last):
  File ".\main.py", line 47, in <module>
    main()
  File ".\main.py", line 34, in __call__
    item[1], item[2], item[3], fields=columns
  File "C:\workspace\python\projects\metamigrate\models.py", line 21, in make
    template = self.environment.get_template(join(self.flavor,'create.j2'))
  File "C:\workspace\python\envs\scipy\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\workspace\python\envs\scipy\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\workspace\python\envs\scipy\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\workspace\python\envs\scipy\lib\site-packages\jinja2\loaders.py", line 168, in get_source
    pieces = split_template_path(template)
  File "C:\workspace\python\envs\scipy\lib\site-packages\jinja2\loaders.py", line 31, in split_template_path
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: mssql\create.j2
```

# Environment
* Python version: 3.6.3
* Jinja version: 2.10

**Comment by davidism** [comment]
Template paths are not filesystem paths. They just happen to behave like that when using the filesystem loader.

As a more general note, Python supports `/` as a separator on Windows, so there's usually no reason to use Windows path separators.
