### ISSUE TITLE
Nested For Loop with Else Causes Exception

### ISSUE THREAD

**Issue by mankyd** [pallets/jinja#86]
Create a for loop with an else clause. In the main clause of the for loop, access {{ loop.index }}. In the else clause, put another for loop. When you render the template, you get an exception:

```
>>> env = jinja2.Environment()
>>> tpl = env.from_string('{% for x in y %}{{ loop.index0 }}{% else %}{% for i in range(3) %}{{ i }}{% endfor %}{% endfor %}')
>>> tpl.render(y=[])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dave/om/trunk/lib/python2.7/site-packages/Jinja2-2.6-py2.7.egg/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "<template>", line 1, in top-level template code
UnboundLocalError: local variable 'l_loop' referenced before assignment
```

**Comment by mitsuhiko** [comment]
Fixed in #637
