### ISSUE TITLE
Cannot filter a list by attributes with a "." prefix.

### ISSUE THREAD

**Issue by pillarsdotnet** [pallets/jinja#900]
The jinja2 [`selectattr()`](http://jinja.pocoo.org/docs/latest/templates/#selectattr) and [`map()`](http://jinja.pocoo.org/docs/2.10/templates/#map) filters cannot filter a list of dicts where the filtering key begins with a  `.` (period) character.  If this behavior is intentional, it should be documented. If unintentional, it should be corrected.

## Expected Behavior

* Example 1 should output:
  ```
  [{'.dotkey': 'foo'}, {'.dotkey': 'bar'}]
  ```
* Example 2 should output:
  ```
  ['foo', 'bar']
  ```

## Actual Behavior

Both examples actually output an error with traceback (copied below).

## Python code

```python
#!/usr/bin/python
from jinja2 import Environment
from jinja2.loaders import FileSystemLoader
from os import getcwd
from sys import argv
print Environment(loader=FileSystemLoader(getcwd())).get_template(argv[1]).render()
```

## Template Code

* Example 1 with [`selectattr()`](http://jinja.pocoo.org/docs/latest/templates/#selectattr) filter:
  ```jinja
  {{ [{'.dotkey': 'foo'}, {'.dotkey': 'bar'}]|selectattr('.dotkey')|list }}
  ```
* Example 2 with [`map()`](http://jinja.pocoo.org/docs/2.10/templates/#map) filter:
  ```jinja
  {{ [{'.dotkey': 'foo'}, {'.dotkey': 'bar'}]|map(attribute='.dotkey')|list }}
  ```

## Full Traceback
```pytb
Traceback (most recent call last):
  File "./j2", line 6, in <module>
    print Environment(loader=FileSystemLoader(getcwd())).get_template(argv[1]).render()
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bobvin/test.j2", line 1, in top-level template code
    {{ [{'.dotkey': 'foo'}, {'.dotkey': 'bar'}]|map(attribute='.dotkey')|list }}
  File "/usr/local/lib/python2.7/dist-packages/jinja2/filters.py", line 880, in do_list
    return list(value)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/filters.py", line 963, in do_map
    yield func(item)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/filters.py", line 77, in attrgetter
    item = environment.getitem(item, part)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute ''
```

## Your Environment
* Python version: 2.7
* Jinja version: 2.10

**Comment by pillarsdotnet** [comment]
Noted.
