### ISSUE TITLE
Build docs error

### ISSUE THREAD

**Issue by Ublimjo** [pallets/jinja#903]
```
Running Sphinx v1.8.0
Original exception:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/data/data/com.termux/files/home/global/jinja/docs/jinjaext.py", line 28, in <module>
    from jinja2._compat import abc
ImportError: cannot import name 'abc'


Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/data/data/com.termux/files/home/global/jinja/docs/jinjaext.py", line 28, in <module>
    from jinja2._compat import abc
ImportError: cannot import name 'abc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension jinjaext (exception: cannot import name 'abc')

Extension error:
Could not import extension jinjaext (exception: cannot import name 'abc')
```

**Comment by davidism** [comment]
This will be addressed as part of larger docs changes being worked on.

**Comment by Ublimjo** [comment]
https://github.com/pallets/jinja/pull/904
