### ISSUE TITLE
Enclosing `{% block %}` in `{% with %}` prevents use of macros defined in parent template

### ISSUE THREAD

**Issue by andreareina** [pallets/jinja#916]
## Expected Behavior
`{% with %}` blocks do not prevent the use of macros defined in a parent template

## Actual Behavior
`jinja2.exceptions.UndfinedError` is raised. The issue is not present if `{% set %}` is used instead.

### parent.html.j2
```jinja
{% macro title() %}title{% endmacro %}
<main>
  {% block main %}
  {% endblock %}
</main>
```

### child-set.html.j2
```jinja
{% extends "parent.html.j2" %}
{% with var = 1 %}
  {% block main %}
    <h1>{{ title() }}</h1>
  {% endblock %}
{% endwith %}
```
### child-with.html.j2
```jinja
{% extends "parent.html.j2" %}
{% set var = 1 %}
{% block main %}
  <h1>{{ title() }}</h1>
{% endblock %}
```

### Python test code
```python
import jinja2

env = jinja2.Environment(loader=jinja2.FileSystemLoader(''))

print("Rendering 'child-set.html.j2'")
print(env.get_template("child-set.html.j2").render())

print("Rendering 'child-with.html.j2'")
print(env.get_template("child-with.html.j2").render())
```

## Full Traceback
```pytb
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    print(env.get_template("child-with.html.j2").render())
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "child-with.html.j2", line 5, in top-level template code
    {% block main %}
  File "child-with.html.j2", line 6, in block "main"
    <h1>{{ title() }}</h1>
jinja2.exceptions.UndefinedError: 'title' is undefined
```

## Your Environment
* Python version: Python 3.7.0 (default, Jul 23 2018, 20:23:10) [Clang 8.0.0 (clang-800.0.42.1)] on darwin
* Jinja version: 2.10

**Comment by crazymug** [comment]
Seems like jinja compiling child-set.html.j2 template wrong way:
```
from __future__ import division, generator_stop
from jinja2.runtime import LoopContext, TemplateReference, Macro, Markup, TemplateRuntimeError, missing, concat, escape, markup_join, unicode_join, to_string, identity, TemplateNotFound, Namespace
name = 'child-with.html'

def root(context, missing=missing, environment=environment):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    if 0: yield None
    parent_template = None
    pass
    parent_template = environment.get_template('parent.html', 'child-with.html')
    for name, parent_block in parent_template.blocks.items():
        context.blocks.setdefault(name, []).append(parent_block)
    l_1_var = 1
    pass
    yield from context.blocks['main'][0](context)
    l_1_var = missing
    yield from parent_template.root_render_func(context)

def block_main(context, missing=missing, environment=environment):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    if 0: yield None
    l_0_title = resolve('title')
    pass
    yield '\n<h1>%s</h1>\n' % (
        context.call((undefined(name='title') if l_0_title is missing else l_0_title)), 
    )

blocks = {'main': block_main}
debug_info = '1=11&3=16&4=27'
```

```
from __future__ import division, generator_stop
from jinja2.runtime import LoopContext, TemplateReference, Macro, Markup, TemplateRuntimeError, missing, concat, escape, markup_join, unicode_join, to_string, identity, TemplateNotFound, Namespace
name = 'parent.html'

def root(context, missing=missing, environment=environment):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    if 0: yield None
    l_0_title = missing
    pass
    def macro():
        t_1 = []
        pass
        t_1.append(
            'title',
        )
        return concat(t_1)
    context.exported_vars.add('title')
    context.vars['title'] = l_0_title = Macro(environment, macro, 'title', (), False, False, False, context.eval_ctx.autoescape)
    yield '\n<main>\n  '
    yield from context.blocks['main'][0](context)
    yield '\n</main>'

def block_main(context, missing=missing, environment=environment):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    if 0: yield None
    pass
    yield '\n  '
```

As we can see compiled code trying to call title() twice, first time in wrong way and context.
If you remove title() call from child-with.html.j2 template you will get this interesting result, which proves that behevior:
```
<h1></h1>
<main>
<h1></h1>
</main>
```

I suppose, there should be handled exception if that usecase does not match jinja's design or one should implement proper processing if such templates are permitted.

**Comment by crazymug** [comment]
I found out that nested ```block``` in ```with``` is valid construction, as shown in test_regressions.py:
```python
    def test_scoped_block(self, env):
        t = env.from_string('{% set x = 1 %}{% with x = 2 %}{% block y scoped %}'
                            '{{ x }}{% endblock %}{% endwith %}')
        assert t.render() == '2'
```
Processing same blocks twice looks like a bug.

**Comment by kevin-brown** [comment]
This is specifically an issue with how `{% with %}` and `{% block %}` work when you're in a child template.

---

Cases that work as expected:
* `{% set %}` outside of a `{% block %}` in a child template
* `{% with %}` inside of a `{% block %}` in a child template
* `{% with %}` outside of a `{% block %}` in a parent template
* `{% block in a child template %}`
* Anything when there is only a single template

Cases that don't work as expected
* `{% with %}` outside of a `{% block %}` in a child template

---

The issue is caused by how `{% with %}` defines a nested frame, and the `{% block %}` tag when inside of a nested frame will force itself to be called. This behaviour, forcing itself to be called, is required for things like the `{% macro %}` tag to be able to generate `{% block %}` tags.

To be more specific, the `{% block %}` tag will force itself to be called if it's not at the top level (so, no nesting) and if it's not in a template that has been extended.

https://github.com/pallets/jinja/blob/9766c179fad831aa6aa2039882fadc7aff6bba2d/jinja2/compiler.py#L814-L818

After looking at how templates are compiled down to Python code, it does not appear as though there is an easy way to change this behaviour without causing a regression. Given that this specific error only appears to occur within a child template, the easy solution would be to move the `{% with %}` call to be _inside of_ the `{% block %}`.
