### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

### ISSUE THREAD

**Issue by jaraco** [pallets/jinja#927]
```
$ pip-run jinja2 -- -Werror -c 'import jinja2.runtime'
Collecting jinja2
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from jinja2)
  Downloading https://files.pythonhosted.org/packages/96/52/eef455862764cb6d6c136aa52c7f9fc4e7c1c644790a7107b1244a2b8a53/MarkupSafe-1.1.0-cp37-cp37m-macosx_10_6_intel.whl
Installing collected packages: MarkupSafe, jinja2
Successfully installed MarkupSafe-1.1.0 jinja2-2.10
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-gvb_ulhy/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-gvb_ulhy/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-gvb_ulhy/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-gvb_ulhy/jinja2/utils.py", line 485, in <module>
    from collections import MutableMapping
  File "<frozen importlib._bootstrap>", line 1032, in _handle_fromlist
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/collections/__init__.py", line 52, in __getattr__
    DeprecationWarning, stacklevel=2)
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```

**Comment by ThiefMaster** [comment]
#867

**Comment by jaraco** [comment]
Sorry for the dupe.  I did search `DeprecationWarning` in the repo first before filing. Github failed me:

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/308610/48663026-2f83f980-ea58-11e8-942a-298bb7069f2b.png">
