### ISSUE TITLE
Template from app is not defined in blueprints

### ISSUE THREAD

**Issue by bwulff** [pallets/jinja#946]
I have a flask app with a static and template folder, there are also blueprints that all have a template folder in their respective directories. 

When trying to extend the base.html that is located in the app template folder in a template that lives in a blueprint template directory, then I get a UndefinedError: 'base' is undefined.

All I read is that Jinja2 first looks at the app template directory and then searches the blueprint template directories in the order in which they have been registered. In my case it seems that the app and the blueprints have their own loader which only sees their own templates (see below) and only the loader for the template seems to be used when rendering the .

---

As a test I'm printing the result of list_templates() after the app was created and ALL blueprints have been registered:
```python
app=Flask(__name__)
print(app.jinja_loader)
print(app.jinja_loader.list_templates())
# ...register blueprints...
print(app.jinja_loader)
print(app.jinja_loader.list_templates())
```
And in the blueprint the same after the blueprint has been created:
```python
login_blueprint = Blueprint('login', __name__, template_folder="templates", url_prefix='/login')
print(login_blueprint.jinja_loader)
print(login_blueprint.jinja_loader.list_templates())
```

## Expected Behavior
The `extends` directive in the blueprint template loads in the template from the app templates folder.

## Actual Behavior
An error is raised: `UndefinedError: 'base' is undefined.`

Also when I run the code with the list_templates() calls in them I see:
```
<jinja2.loaders.FileSystemLoader object at 0x7ff1828ee150>
['base.html']
<jinja2.loaders.FileSystemLoader object at 0x7ff1828ee350>
['login.html']
<jinja2.loaders.FileSystemLoader object at 0x7ff1828ee150>
['base.html']
```
Which is not wrong: the ...350 instance of the loader only sees the login.html from the blueprint tempalte folder and the ...150 instance of the loader only sees the base.html from the app template folder. 

But somehow the app's loader is not asked when rendering the blueprint template and the `extends` is reached.

## Template Code
```jinja
{% extends base.html %}

{% block content %}

<div class="container">
    <div>Login form</div>
</div>

{% endblock %})

```

## Full Traceback
```pytb
portal_1  | Traceback (most recent call last):
portal_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
portal_1  |     return self.wsgi_app(environ, start_response)
portal_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
portal_1  |     response = self.handle_exception(e)
portal_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
portal_1  |     reraise(exc_type, exc_value, tb)
portal_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
portal_1  |     response = self.full_dispatch_request()
portal_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
portal_1  |     rv = self.handle_user_exception(e)
portal_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
portal_1  |     reraise(exc_type, exc_value, tb)
portal_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
portal_1  |     rv = self.dispatch_request()
portal_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
portal_1  |     return self.view_functions[rule.endpoint](**req.view_args)
portal_1  |   File "/app/gpucloud/modules/login/__init__.py", line 9, in index
portal_1  |     return render_template('login.html', username_helptext='Using LDAP directory.')
portal_1  |   File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
portal_1  |     context, ctx.app)
portal_1  |   File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
portal_1  |     rv = template.render(context)
portal_1  |   File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
portal_1  |     return self.environment.handle_exception(exc_info, True)
portal_1  |   File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
portal_1  |     reraise(exc_type, exc_value, tb)
portal_1  |   File "/app/gpucloud/modules/login/templates/login.html", line 1, in top-level template code
portal_1  |     {% extends base.html %}
portal_1  |   File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
portal_1  |     return getattr(obj, attribute)
portal_1  | UndefinedError: 'base' is undefined
```

## Your Environment
* Python version: 2.7.15
* Flask: 1.0.2
* Jinja version: 2.10

**Comment by bwulff** [comment]
Well, I solved the issue by changing
```{extends base.html}```
in the template to 
```{extends "base.html"}```
So i was asking for a template object `base` all the time and not asking for the file `base.html`.
