### ISSUE TITLE
Operations on StrictUndefined should raise the UndefinedError

### ISSUE THREAD

**Issue by Porkepix** [pallets/jinja#948]
First, this is a problem encountered through ansible.
Original issue onto ansible issue tracker is https://github.com/ansible/ansible/issues/52494 and might have better description. I here used test case written by someone of Ansible's project as I never used jinja directly but only through Ansible.

Issue is about trying to access an undefined key in a dictionary.
There are two cases that receive pretty different reaction from Ansible. One is precise and correctly locate the issue and have a clear error message, not the other one.

## Expected Behavior
Error message should be exactly the same one considering in both cases issue is the same: user try to access an undefined key in the dictionary. The whole template also shouldn't be printed.

## Actual Behavior

If accessing to an undefined key in the dictionary from/with conditional statements, error message is misleading and also don't locate correctly the problem and print the whole template as an error.

## Template Code

First template
```python
import jinja2
e = jinja2.Environment(undefined=jinja2.StrictUndefined)
t = e.from_string("{{ test_dict['foobar'] }}")
t.render(test_dict={})
```

Second template
```python
import jinja2
e = jinja2.Environment(undefined=jinja2.StrictUndefined)
t = e.from_string("{{ 'test' not in test_dict['foobar'] }}")
t.render(test_dict={})
```
## Full Traceback
First template render

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matt/venvs/ansibledev/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/matt/venvs/ansibledev/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/matt/venvs/ansibledev/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matt/venvs/ansibledev/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'foobar'
```
Here we can see that Jinja can tell exactly the missing key and locate precisely the line in a template.

Second template render
```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matt/venvs/ansibledev/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/matt/venvs/ansibledev/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/matt/venvs/ansibledev/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/matt/venvs/ansibledev/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: argument of type 'StrictUndefined' is not iterable
```
Here, exception is pretty obscure. In Ansible you even get two errors, and in-between jinja just give the whole template as an error.

## Your Environment
* Python version: 3.7.2
* Jinja version: 2.10

**Comment by davidism** [comment]
Related to #811, a similar thing needs to be fixed for `DebugUndefined`.

**Comment by EtiennePelletier** [comment]
Salut @Porkepix !
See comments by Ansible folks on https://github.com/pallets/jinja/pull/997. See also my explanation on #811. Basically, a new class of Undefined is going to be released along next jinja2 version. In the meantime, Ansible developed their equivalent called AnsibleUndefined that basically has the same functionality.

When using these instead of StrictUndefined, your first template example will return an empty string as `test_dict['foobar']` is undefined. The second template example will however fail because using the `in` keyword on an undefined item. This tries to iterate over the undefined object, which is not allowed and will raise an UndefinedError.
